### ISSUE TITLE
Follow logs

### ISSUE THREAD

**Issue by tbarusseau** [Nukesor/pueue#125]
**Is your feature request related to a problem? Please describe.**
`pueue log` only displays the already available logs, then exits.

**Describe the solution you'd like**
`pueue log -f`/`--folow`, which would display the available logs in real time, until interrupted through a `Ctrl + C` or other, similar to how `tail -f` behaves on UNIX environments.

**Comment by Nukesor** [comment]
What about the `pueue follow` subcommand?
It's also documented over [here](https://github.com/Nukesor/pueue/wiki/Get-started#see-whats-going-on)

**Comment by tbarusseau** [comment]
Uh, I was fully expecting that feature to be an option of the `log` subcommand, so much that I didn't even see it in the `--help` page. Thanks!

**Comment by d33tah** [comment]
I feel like pueue logs --follow should be an alias to pueue log. I was just looking for the same feature and only found it thanks to this issue, so it might be a UX bug. Pinging @Nukesor

**Comment by Nukesor** [comment]
The problem is, that `follow` and `log` have very different semantics.

`log` can be run for multiple tasks, it can be exported as json and it has special parameters for limiting output
`follow` on the other hand can only be run for a **single** task and is basically a simple stream of the stderr or /stdout output.

I don't see a way of aliasing `follow` behind `log` without breaking consistency across the board.

There is literally no overlap between `follow`'s and `log`'s arguments, except the **first** task id.

**Comment by d33tah** [comment]
@Nukesor OK, that is convincing. Perhaps then having a note in the --help that follow exists could help?

**Comment by Nukesor** [comment]
That is definitely an option and hopefully avoids some future confusion :)

**Comment by Nukesor** [comment]
A hint has been added in c3afbda
