### ISSUE TITLE
`reset` command should *always* ask user confirmation if there are running processes on the queue

### ISSUE THREAD

**Issue by quebin31** [Nukesor/pueue#140]
**Is your feature request related to a problem? Please describe.**
It's possible to run `pueue reset` and basically stop and remove all your running jobs without confirmation, this shouldn't be allowed by default.

**Describe the solution you'd like**
Prompt a confirmation if there are running jobs on the queue and the user wants to reset the state, optionally add a flag `--force` (only long option for clarity on the intent of forcing) to `pueue reset` if the user still wants to forcibly reset.

**Describe alternatives you've considered**
None.

**Additional context**
Happened to me today, luckily the process somehow didn't finish.

**Comment by Nukesor** [comment]
Well, this is probably a good idea.
If the confirmation should only be displayed when jobs are running, we need to add some extra logic, though.

This removes the `Reset` command from the simple "ping-pong" commands, since we have to get the daemon's task state before doing anything. Nothing dramatic, though.

Take a look at `client::client::handle_complex_command`. It should give a you a good starting point on how to do this :).

Feel free to start coding :).
If you don't plan to code this yourself, I might get to it. However, I'm pretty busy right now.

**Comment by quebin31** [comment]
I'll take a look at the code and try to add the feature, thanks!
