### ISSUE TITLE
Option to set name or print job_id only

### ISSUE THREAD

**Issue by elbaro** [Nukesor/pueue#151]
I want to spawn a few jobs with dependencies.
This is using bash regex:

```bash
out=$(pueue add -- echo 123)
[[ $out =~ .+id[[:space:]](.+)\).+ ]]
job_id=${BASH_REMATCH[1]}
pueue add --after $job_id -- echo 456
```

**Describe the solution you'd like**

with `--name`
```
pueue add --name job1 -- echo 123
pueue add --after job1 -- echo 456
```

with `--print-job-id`
```bash
job_id=$(pueue add --print-job-id -- echo 123)
pueue add --after $job_id -- echo 456
```

**Comment by Nukesor** [comment]
Hm. I see how using dependencies can be annoying when scripting stuff.

In my opinion, the `--print-job-id` flag is the more elegant solution, since it solves the problem just as well and doesn't need an additional field on the task or column in the `status` overview. This should be implemented in a few minutes :D

**Comment by elbaro** [comment]
Thanks, that was fast.
In fact I found `--name` is useful for other reasons. I will create a separate issue for this.
