### ISSUE TITLE
Labeling tasks

### ISSUE THREAD

**Issue by elbaro** [Nukesor/pueue#155]
These long commands differ only by 1~2 parameters. To identify any task, I have to read the long command section to find the difference.

![image](https://user-images.githubusercontent.com/1851290/102681195-cbb5f700-4202-11eb-83a1-019067b58f73.png)

**Describe the solution you'd like**

Add optional `--name` (`--label`, `--id`, `--desc`, or even `--tags`).

I have no preference on details, for example whether duplicated names should be allowed, error, or suffixed.

**Comment by Nukesor** [comment]
I like the `label` option :)

This should be another optional column that's only displayed, if there's actually a task that has a label.
I'm not sure where to position this column though. After `Exitcode`?

This shouldn't be too hard to implement either, since there's no additonal logic connected to it.

Regarding the previous issue (the` --print-task-id thingy`), I think this should keep its current logic and return the actual task id.
That way the `--after` flag can enforce actual id's and we don't have to add any logic to check whether we just got an id or a label.


I'm currently doing a lot of final polishing and refactoring in preparation of the first big v1.0 Release candidate.
This is definitely something that should be added to v1.0 :)

It would be awesome, if you find time to implement this yourself in a timely manner.
If you don't manage to find some time, I'll probably implement it myself ;D

Just give me a ping, on what your plans are :)

**Comment by elbaro** [comment]
Sorry I missed the chance.

I tested #157 and it works well. Thanks for the great project.

**Comment by Nukesor** [comment]
Perfect :)
You're welcome
