### ISSUE TITLE
Multiple nodes with shared pueued instance

### ISSUE THREAD

**Issue by ghuls** [Nukesor/pueue#163]
We have a cluster (with interactive nodes) with a shared HOME dir. I am trying to run pueue on multiple nodes.
If I use the socket option, I manage to run jobs on each nodes, but the log file can get corrupted (having a different config file with a different socket file is possible of course).
With the TCP option, all jobs will run on the same node.

It would be nice to see the status of all jobs over all nodes add jobs from all interactive nodes (that will run on the node from which they are submitted by default or run on a specific node if specified).

Are there any plans in that direction?

**Comment by Nukesor** [comment]
Hm. I never thought about a scenario like this.

In theory, it should be enough to prevent writes from two different pueue instances to the `local/share/pueue/state.json`, since this is the only file that should be written to by multiple instances. It is guaranteed, that a single `pueued` instance only writes with one thread at a time, since this needs to acquire a `Mutex`.

However, this only solves the problem of file corruption. The pueued instances will still not synchronize, if, for instance, one of the instances adds a task or resets the queue.

Running and synchronizing multiple instances was never part of Pueue's scope and I think that it won't be in the future.

Don't get me wrong, this would be pretty cool, but this will most likely require a huge amount of work and it adds a pretty hefty layer of complexity on top of a already complex program.

I think that this is something that should be its own project. Pueue should stay a project for "personal" usage.
A neat commandline helper, rather than a task manager for distributed systems.

**Comment by Nukesor** [comment]
Closing for now :)

Feel free to use the existing code to create a fork!
A good start would probably be to extract the Taskhandler into a stand-alone binary, which can act as a worker-instance and gets it's tasks from a singular daemon instance.
That way you would have a single-source of truth and an arbitrary amount of worker instances.
The only remaining problem would be the syncing and forwarding of any state changes.
