### ISSUE TITLE
Error: Couldn't find username for current user

### ISSUE THREAD

**Issue by shhong** [Nukesor/pueue#173]
I downloaded the 0.11.1 release and run it in CentOS 8. I got “Error: Couldn't find username for current user” every time both for pueue and pueued. I checked that `whoami` works fine and $USER shows the correct username. Any idea?

**Comment by Nukesor** [comment]
Weird. The code for getting the username looks like this:

```
    use users::{get_current_uid, get_user_by_uid};

    let user = get_user_by_uid(get_current_uid())
        .ok_or(anyhow!("Couldn't find username for current user"))?;
```

https://docs.rs/users/0.11.0/users/fn.get_user_by_uid.html
This uses the system's user database, which might not be available due to security measures?

An alternative could be to use the [whoami](https://docs.rs/crate/whoami/1.1.0) crate.

**Comment by Nukesor** [comment]
Could you try and check if pueue works, if you install directly from this branch?

```
git clone git@github.com:Nukesor/pueue
cd pueue/pueue
git checkout switch_to_whoami
cargo run --bin pueue -- status
```

**Comment by shhong** [comment]
switch_to_whoami works fine. Thanks!

**Comment by Nukesor** [comment]
New version is released :)
You should be good to go
