### ISSUE TITLE
[BUG] Switching tasks doesn't update dependencies

### ISSUE THREAD

**Issue by farid-fari** [Nukesor/pueue#185]
**Describe the bug**
If two tasks are switched, their new numbers aren't updated in the dependencies of other tasks.

**To Reproduce**
1. Add two tasks by executing twice `pueue add -- sleep 60`, they have ids 1 and 2
2. Then create a third task that depends on these two, `pueue add -a 1 2 -- sleep 60`, with id 3
3. Then create a fourth task again, `pueue add -- sleep 60`
4. Switch the final task with one of the initial tasks `pueue switch 1 4`
5. Task 3 will depend on the newly added task rather than the initial task it depended on

**Expected behavior**
It depends on how you view the switch command, if it's supposed to help you correct mistakes in tasks then the current behaviour could be expected, but the way I see it (and it is described in documentation) is to reorder tasks. In that case, it would make more sense for it to switch dependencies as well.

**Comment by Nukesor** [comment]
Nice find :D

This should actually be an easy fix, but it's probably good to write a proper test for this as well.
We will have to iterate over all tasks and check if any of these tasks use the affected tasks as a dependency.

The code for this is completely isolated in `daemon/network/message_handler/switch.rs`.
Examples for tests can be found the `clean.rs` in the same directory.

Feel free to go ahead and fix this yourself :) Just ping me, so I know what's  going on.

Otherwise, I'll do this as soon as I find some time to do so.

**Comment by Nukesor** [comment]
FYI
I started working on this

**Comment by Nukesor** [comment]
Fixed in 8b50c55d916f7c5348d0dbcad243a7bea25c3122
