### ISSUE TITLE
Including sdtout and stderr Into Callback

### ISSUE THREAD

**Issue by umbriquse** [Nukesor/pueue#196]
**Is your feature request related to a problem? Please describe.**
This request isn't related to any particular problem.

**Describe the solution you'd like**
I would like to be able to include the stdout and stderr into the callback.

**Describe alternatives you've considered**
I looked for a way to include the stdout/stderr into the callback or just retrieve it from somewhere, but couldn't find a way to include it.

**Comment by umbriquse** [comment]
This is a bit related to #186, But I think it's different enough to warrant it's own issue.

**Comment by Nukesor** [comment]
It's actually not related, since the daemon is responsible for calling the callback.
Thereby there wouldn't be any need to communicate.

But this might also lead to a few other issues:

- Logs for long-running commands tend to be super long. We would have to fully load those logs into memory, which already caused issues in the past. The machines of a few people actually ran out of memory because of this.
- Another thing that might cause issues is that log output isn't properly shell-escaped. We could no longer guarantee, that the generated command will be properly executed, since there might be shell escape-sequences in there.

To be honest, I'm not exactly sure why you would need this, could you explain your use-case?

Just to explain my confusion: My notification pop-ups usually take very little screen space.
I imagine, having a lot of log output in there would be either super obtrusive (since it takes a lot of screen space) or confusing (lots of line-breaks due to small line width).

**Comment by umbriquse** [comment]
I wouldn't necessarily want to view the entirety of the logs. Just have the option to view either the output of the finished program or the error message that is given.

This feature came to mind because I have some long running programs and would like to know either what the output of the program was or (if it errored) the error message and it's stacktrace.

Also the notification system is through an online messaging system so I would be able to view many lines.

**Comment by Nukesor** [comment]
I see, so it would be enough to get the last few lines of code (10?) and work with those?

**Comment by umbriquse** [comment]
If there has to be a hard limit, I would prefer something a bit larger like 30 lines. This is mostly due to some stacktraces that I've viewed. I can see why a hard limit would be preferable to being notified all prints that a program performs. 

I am curious if it would be possible to do a keyword search for "ERROR" in the error message and return everything after that, and have like a 30 line limit for the programs output?

Or would it be possible to have the number of view lines as a parameter (with a default value) that the user could change?

**Comment by Nukesor** [comment]
Implemented in https://github.com/Nukesor/pueue/pull/198/commits/55e2f94dcc9f204f97648479bbddb6ebcf22b386

**Comment by Nukesor** [comment]
The release candidate is now available.
`cargo install pueue --version 1.0.0-rc.1`
