### ISSUE TITLE
Having an option to send SIGTERM instead of SIGKILL to a program.

### ISSUE THREAD

**Issue by dovahcrow** [Nukesor/pueue#202]
**Is your feature request related to a problem? Please describe.**
First thanks for building this fantastic library! I was really excited to include `pueue` into my daily command-line workflow the moment I found it. 

Basically, I have some programs react with SIGTERM to do a graceful shutdown. However, it seems like `pueue` will send SIGKILL to the program for`pueue kill`, which is not capturable. 

**Describe the solution you'd like**
Maybe add a `-s` parameter to `pueue kill` to allow us select the signal?

**Comment by Nukesor** [comment]
You're welcome :)

Actually, this feature existed in the previous (python) version of Pueue :D.
This is definitely something we could pick up and implement again.

In general, I think that this is a neat feature and it shouldn't be too hard to implement, since we already have signal sending logic in place.

As far as I remember, Windows doesn't have anything like Unix Signals, wo we have to take care that this feature isn't included in the Windows build. Another thing that might make a few problems is the current process handling library used for MacOS (psutil), which is pretty much abandoned. 

It also might allow users to send `SIGSTOP` or `SIGCONT` to processes, circumventing Pueue's integrated logic. This might in term lead to weird edge-cases, but people using this feature hopefully know what they're doing^^.

**Comment by dovahcrow** [comment]
Yep totally agree. Another thing might make it complicated is that SIGKILL guarantees the process will exit but SIGTERM doesn’t. This changes the semantic of pueue kill command. 

An alternative I imagine is adding a `signal` sub command rather than temper with the existing kill command. Then we can the use conditional compilation to make the `signal` command only exist under Linux.

**Comment by Nukesor** [comment]
The `signal` subcommand actually sounds like very good idea.
That way we could clarify that via help/docs, that this might lead to unpredicted behavior.

Feel free to start coding on this :)

I might start working on this myself at some point, but right now I'm in the process of cleaning up the project and planning the v0.13 release. It might take a while for me, to take a look at this.

**Comment by Nukesor** [comment]
FYI I started working on this. I couldn't restrain myself.

**Comment by dovahcrow** [comment]
> FYI I started working on this. I couldn't restrain myself.

lol I was planning to do it during the weekend ... 

Thanks! I'll test it then.

**Comment by Nukesor** [comment]
The release candidate is now available.
`cargo install pueue --version 1.0.0-rc.1`
