### ISSUE TITLE
[BUG] Deadlock when resuming tasks

### ISSUE THREAD

**Issue by dovahcrow** [Nukesor/pueue#208]
**Describe the bug**
I'm getting a deadlock at this line https://github.com/Nukesor/pueue/blob/v0.13/daemon/task_handler/messages/start.rs#L65 after issued `pueue start -a` with an existing state of a bunch of queued tasks.

If I understand it correctly, https://github.com/Nukesor/pueue/blob/v0.13/daemon/task_handler/messages/start.rs#L19 already locks the state and only releases the lock at the function exit. This results in a guaranteed deadlock for L65. 

Is it ok to just remove L65 since we already have the state locked?

**Comment by Nukesor** [comment]
Yep. That was it.
Thanks for the analysis and fix!

I completely remodeled the way mutexes are used in the task handler for v0.13. I.e. get the mutex for the full duration of the function instead of multiple times for shorter durations. The idea behind this, was to get something that's a little more like atomar transaction-like behavior.

I already fixed a few deadlocks that occurred due to these changes, but it looks like I wasn't thourough enough :D

This stuff is btw. the main reason why v0.13 isn't merged yet. I'm not feeling too comfortable yet.

Tbh. Pueue definitely needs some integration tests.

**Comment by dovahcrow** [comment]
@Nukesor Yeah I just met another deadlock after killing a group, adding in a new task, and `pueue start` the group. However after I restarted the daemon with `-vv`, the deadlock was gone. So I'm not sure what was going on but definitely, there is another deadlock somewhere.
