### ISSUE TITLE
Worker id environment variable

### ISSUE THREAD

**Issue by Flova** [Nukesor/pueue#218]
**Is your feature request related to a problem? Please describe.**
It would be cool to know the id of the worker, when the queue is progressed using a number of parallel workers.
Let's say you have a queue of deep learning experiments and multiple GPUs. In theory, you are able to work on this queue in parallel, but in reality, the parallel tasks need to be assigned to different GPUs. This is often done using an environment variable that is set manually, which is not really feasible for the dynamic scheduling using the parallel queue.

**Describe the solution you'd like**
Add an environment variable like `PUEUE_WORKER_ID` that returns 0 in the first running parallel job and `n` in the n'th parallel running job, where the maximum `n` is set in `pueue parallel`.

**Describe alternatives you've considered**
Using the GPU utilization to determine which one we use. This could be quite error-prone, since not all tasks use the complete GPU constantly and tasks might fail if both jobs want to allocate a large memory portion.

**Comment by Nukesor** [comment]
I think I understand your issue.

The command would then be something like
```
./train --gpu $PUEUE_WORKER_ID some_other_parameters`
```
and the command/script would resolve the ID and map it to the respective gpu?

For now, this isn't an easy fix, as Pueue doesn't have a concept "workers" yet.
It simply looks at the amount of the amount of currently running tasks and starts new tasks until the limit for the group is reached. It's a pretty stupid way of scheduling, but it works.

Adding the concept of workers might lead to some weird edge-cases though.
One thing that instantly pops into my mind is how this should behave, if you force-start tasks manually.
Should the `$PUEUE_WORKER_ID` simply increase, e.g should a new "worker" slot be created, that'll be dropped as soon as another slot is free?

For instance, take a group with two slots:
- Add 10 tasks `task1-10`
- `tasks1-2` get automatically started -> they block `worker1-2`.
- Force start of `task3` -> Create and block new `worker3`
- `task1` finishes -> `Worker1` is freed, but there are still two slots occupied in the queue.

What's the right move in this situation.
-  Spawn `task4` with `worker1`. This effectively blocks `worker1` from working.
-  Wait until `task3` finishes, delete `worker3` and continue. If we choose this path, manually starting tasks permanently increases the amount of available slots until the additional tasks finished. This is probably the worse solution, as this sounds like a rather bad side-effect.

The term "worker" might also be somewhat confusing, as pueue doesn't have any workers.
It directly spawns subprocesses, while workers or worker/pools usually consist of a thread-/processpool.
After thinking about this, this is probably just nitpicking :D. "Worker" is probably still a good naming convention, as people will have an easier time to understand the concept behind this variable.

Still, this feels a little like putting a load-balancer for external resources on top of Pueue, which I'm not a huge fan of.
It somehow reminds me of [this issue](https://github.com/Nukesor/pueue/issues/170) from a while back. 
The goal of Pueue is to be a handy, but relatively simple tool for handling and scheduling long-running shell commands.
It's true that load-balancing is also part of a full-featured scheduler. However, building a proper load-balancer for generic commands would be too much added complexity.

I think, I like the idea of simply adding an environment variable. That way we provide the user with the tools to build their own customized load/resource-balancing.

I'll think about this some more, but this could work.
We would have to do some prototype implementations and proper testing. As I said, this might introduce a few new edge-cases, as we'll be changing some integral parts of the `TaskHandler`.
However, pretty much all of this changed/added functionality is encapsulated in the `TaskHandler` code.

**Comment by Nukesor** [comment]
While we're at it, we could leak the `$PUEUE_GROUP` into the environment as well :)

**Comment by Flova** [comment]
> the command/script would resolve the ID and map it to the respective gpu?

Exactly!

> The term "worker" might also be somewhat confusing, as pueue doesn't have any workers.

Indeed that makes things a bit more tricky and adds more edge cases-

> Still, this feels a little like putting a load-balancer for external resources on top of Pueue, which I'm not a huge fan of.

I agree with you that it is better to keep tools simple and handle new features with caution, but it would be also cool to get more information about the current state of the tool.

> I'll think about this some more, but this could work.

Cool! Thanks.

**Comment by Nukesor** [comment]
I started tinkering around with this and I'll just use this issue as a dump for insights, stuff that needs to be done and/or taken into account.

## Groups:

Grouping in general is one of the more troublesome features of Pueue.
It's the only option that can be changed during runtime and that has direct impact on how Pueue works.
-> You increase the count of parallel tasks, new tasks need to be spawned.
-> Individual groups can be paused/started
-> Groups can be added, removed during runtime.

Groups are problematic since two different types of states of groups live inside of Pueue.
1. The configuration of how many tasks ran in parallel. This is stored in the `Settings` struct and persistet in the config file.
2. The current state of the Group `Started/Paused`. This lives in the `State` struct and is part of the current application state.

Until now, the `TaskHandler` didn't need to store any representation of groups, as the info in the `Settings` and the shared `State` were enough.

As we're planning to introduce group-based worker pools/slots to Pueue, this needs to change.
As a result, The datastructure for the storage of subprocess handles now changes from a simple.
```
BTreeMap<task_id, Handle>
```

to this:
```
BTreeMap<group, BTreeMap<group_worker_id, (task_id, Subprocess handle)>
```

This structure is necessary, as we have to remember worker ids (0-X) depending on the task's group.
Hence, we not only have to sync `Settings` and `State` on any changes to groups, but also the `TaskHandler`.


## Things that need to be done

- We have to adjust the current logic to use that new datastructure. I already did that in this draft PR https://github.com/Nukesor/pueue/pull/220.
- Handle the manual addition of groups and propagate these changes to the `TaskHandler` via our `mpsc` channel.
- Handle the manual removal of groups and propagate these changes to the `TaskHandler` via our `mpsc` channel.


## Problems

### Deletion of Groups

I'm not exactly sure what's the best way to handle the removal of groups.
The current behavior is, that these tasks will simply be moved into the `default` queue. However, with the new datastructures, this could lead to some weird behavior.

For example:
Group "default" has 2 Slots, both are occupied by task1 and task2.
```
BtreeMap["default"] = {
    "0" = (1, ProcessHandle0)
    "1" = (2, ProcessHandle1)
}
```

Group "special" has 2 Slots, both are occupied by task3 and task4.
```
BtreeMap["default"] = {
    "0" = (3, ProcessHandle2)
    "1" = (4, ProcessHandle3)
}
```

When deleting group `special`, we now have to merge this group with the default group.
Should that look like this?
```
BtreeMap["default"] = {
    "0" = (1, ProcessHandle0)
    "1" = (2, ProcessHandle1)
    "2" = (3, ProcessHandle3)
    "3" = (4, ProcessHandle4)
}
```
It feels kind of dirty, as we're merging two worker pools that don't have any relationship to each other. The `default` group is now running two tasks that're using a different "type" of worker.

One possible solution to this inconsistency, would be to simply prevent users from deleting groups, if there are any groups in it. I guess nobody would have a problems with this, as it seems to be a pretty big edge-case anyway. At least I cannot think of a scenario, where this is critical to have.

**Comment by Nukesor** [comment]
@Flova Could you test, whether the current state of the branch is working for you?

Adding/removing groups doesn't work yet, but the raw worker pool logic should be fine.

**Comment by Nukesor** [comment]
Group addition and removal should now work as well.
I think the test coverage should be enough, but I would really like to get some real-world testing.

**Comment by Flova** [comment]
I am currently on vacation, but I may find the time to launch my next batch of experiments in the next days. I would test this when I launch them. Thanks for your effort btw.!

**Comment by Nukesor** [comment]
Fourth release candidate v1.0.0-rc4 is out and includes this feature
```
cargo install pueue --version 1.0.0-rc.4
``

**Comment by Nukesor** [comment]
I'm going to close this issue for now :)
Anyhow, I'm still interested if the feature works as expected and is properly implemented for your use-case!
