### ISSUE TITLE
[BUG] pueue follow prints nothing in 1.0.1

### ISSUE THREAD

**Issue by sourcefrog** [Nukesor/pueue#228]
```
> cargo install pueue
    Updating crates.io index
     Ignored package `pueue v1.0.1` is already installed, use --force to override

> nice pueued -d
Pueued is now running in the background

> pueue add -- cargo install bat
New task added (id 0).

> pueue status
Group "default" (1 parallel): running
────────────────────────────────────────────────────────────────────────────
 Id   Status    Command             Path                     Start      End 
════════════════════════════════════════════════════════════════════════════
 0    Running   cargo install bat   /home/mbp/src/conserve   12:16:16       
────────────────────────────────────────────────────────────────────────────
> pueue follow 0
[nothing happens, while the task is still running]

^C

> pueue log 0|head
┌───────────────────────────────────┐
│ Task 0:    completed successfully │
└───────────────────────────────────┘
Command: cargo install bat               
   Path: /home/mbp/src/conserve          
  Start: Sat, 21 Aug 2021 12:16:16 -0700 
    End: Sat, 21 Aug 2021 12:17:06 -0700 

stderr:
    Updating crates.io index
```

This is on Linux. It seems to be reproducible. I might dig in to it later.

**Comment by Nukesor** [comment]
The output is printed to stderr
Just call `pueue follow 0 -e`

**Comment by sourcefrog** [comment]
This might be a confusing UI for other people too...

**Comment by Nukesor** [comment]
I'm not sure what's the best way to work around this to be honest.

At the very beginning of the project, the decision has been made to record stderr and stdout into two separate files.
Sadly, it's no longer possible to merge them back together without any additional metadata, which would invalidate the approach of simply piping the outputs to files.

Having them in files is crucial, as logs can become several gigabytes big, which will break some peoples PCs, due to too much RAM usage.
Thereby, we would have to use some kind of streaming file format, which supports multiple input sources with meta data for each entry (timestamp + origin). (It's also super hard to differentiate between connected multi-line log output and several unrelated log outputs). Since supporting such a setup is quite complex and it never seemed crucial to me, it has never been done. 

However, this of course comes with some limitations. Such as, that these streams can no longer be merged afterwards.

As a result, we have to also differentiate between `stdout` and `stderr` when calling `pueue follow`, as it would also be super confusing to get all something like
```
STDOUT logs only....
....
....
....
STDERR logs only....
....
....
....
Now that we're on the newest line, we try try to mix them together in a single output.
But this might be akward as we don't know which stuff belongs together.
....
....
```

So yes, I agree that it might be confusing that you only see `stdout` by default, but my guess is that it's not that easy to set this up in a different way.

Anyhow, it might very well be, that I'm incorrect and there's a simple solution I'm overlooking.
In that case, please correct me! It would be awesome, if we get this fixed in a simple and elegant way.

I'm always open to feature PRs that improve Pueue's UI and internal handling :)

**Comment by sourcefrog** [comment]
I don't think you need to strictly differentiate them: terminals people normally use don't do so. As long as they're not mixed inside a single line I think it won't be too confusing, even it the output is in a somewhat different order than people would see if they ran the program directly in a terminal. At any rate it would be less confusing than not showing it at all. 

I think it's pretty common for programs to say something to stderr, but relatively rare for them to depend on precise ordering of stdout vs stderr, partly because this is so easily disrupted by e.g. `|less`.
