### ISSUE TITLE
Failed to run tasks with admin privilege (sudo)

### ISSUE THREAD

**Issue by minhng92** [Nukesor/pueue#229]
Hi, I found **pueue** on reddit and tried it recently. It makes me work more productive. Sometimes I need to run scripts with admin privilege:
`sudo ./my_script`

I don't know how to handle command with "sudo" in **pueue**. Below screenshot is just an example, the log shows error:

`sudo: no tty present and no askpass program specified`

![Screenshot from 2021-08-23 01-43-12](https://user-images.githubusercontent.com/34470011/130366384-b958dc1e-3b47-42f4-af27-114b24c38617.png)

Command with "sudo" is added, but it failed to run. No password prompt is shown to me so I cannot fill in the passwrd.

Thanks,
Minh

**Comment by Nukesor** [comment]
The processes aren't run within a terminal, but on a stand-alone shell process.
Hence, sudo doesn't know it has to listen on `stdin` for the password.

The error message looks like you can specify an askpass program?
This might be a possible solution.

However, this is nothing that can easily fixed by Pueue, since this requires all processes to be spawned in a pty. Working with PTYs is super annoying, which is why this won't be implemented.

A possible solution is, to not reqiure sudo passwords for specific commands, but this is of course a security risk.

I guess the askpass solution is probably the best approach to fix this.

**Comment by Nukesor** [comment]
Closing for now, as this won't be fixed on Pueue's end.

Feel free to post your solution, though. This might be useful for other people.

**Comment by d33tah** [comment]
I also came across this limitation - I was trying to pipe data to an invocation of `docker run` and I needed root do to that.

I worked around it by doing `sudo true` before running pueued again. It worked, but it's hacky.

Given that askpass was already mentioned, perhaps it makes sense to think of whether pueue could interface with sudo somehow?

The alternative that comes to my head is to use `sudo -S` to read password for stdin, but for some reason it didn't work during my experiments. If that is preferred, I think that `pueue send` should have a way to read data from process's stdin because otherwise any passwords can be captured by watching executed processes.

**Comment by Nukesor** [comment]
I aggree that `pueue send` should have an option to read from `stdin`. That would be quite convenient.

However, i'm not sure what you mean by "watching executed processes". Could you elaborate your attack model?

**Comment by Nukesor** [comment]
I'm also kind of against tight integration with sudo.

If running things as root is a regular scenario, it would be probably better to run a second `pueued` instance as root.
With the planned profiles feature #244, one could easily switch between the two instances.
That way one would have a clear separation between commands run as the current user, root or any other user.

**Comment by d33tah** [comment]
> However, i'm not sure what you mean by "watching executed processes". Could you elaborate your attack model?

Basically, someone sniffing on /proc to see argv of each process executed and capturing a password this way. Some things just shouldn't fly as argv.

**Comment by mpeter50** [comment]
@Nukesor how should one use the profiles feature for this?

If I start an instance of pueued as root, it will use `/root/.local/share/pueue` as the place to store it's files.
The socket file there will have access restricted to only allow writes for root, and this means I would also need to run the client as root for it to be able to write to the pueued socket. (or allow writes for e.g. my usergroup, but then any program I run will be able to use sudo without asking for a password..)

If I also start the client as root, it too will use the above mentioned directory for it's files, and it won't read my personal configuration for the profiles defined in there.

**Comment by Nukesor** [comment]
Pueue is designed to allow communication to a remote daemon.

1. Start the daemon as root
2. Place the unix socket somewhere where your user can read it.
3. Set `read_local_logs: false` in your client's profile config. That way, the client will request the logs from the daemon rather than reading it from the disk.
4. Set the correct unix socket path in your client's profile config.
5. Copy the secret to your unprivileged user and set the path in the client's profile config.

**Comment by mpeter50** [comment]
This means I can't put this behind a "sudo" call or something else requiring my confirmation if I want to use profiles, right?

**Comment by Nukesor** [comment]
I'm not sure what you mean.

If you call pueue as `sudo`, you call it as root and thereby look for instances of `pueued` that were spawned by root.

With my guide, you can spawn a `pueued` instance as root and connect with a non-root client (without sudo) to that instance...

**Comment by mpeter50** [comment]
I meant that if I understand it correctly, this means that if I have access to a different user's pueued's socket (either root or just an other linux user account), then I and any software that I run can act as that other user, without an additional permission prompt (like sudo's password prompt, or polkit's prompt) before doing so. This can be a problem if that software I run does this without me knowing it (either intentionally, or because it has been exploited).
I've only mentioned `sudo` as an example that prompts me for my permission before continuing.

Am I correct, or did I miss something that makes this not possible?

**Comment by Nukesor** [comment]
>     5. Copy the secret to your unprivileged user and set the path in the client's profile config.

As I mentioned, you have to copy the secret and link to it in the config.
The secret is a 512Byte secret. If you find a way to easily bruteforce this, please open a separate ticket and I'll think about a more appropriate authentication method.
