### ISSUE TITLE
Move jobs between groups?

### ISSUE THREAD

**Issue by joehillen** [Nukesor/pueue#231]
**Is your feature request related to a problem? Please describe.**

I currently have a job that's going to take at least a week (btrfs balance). I'd like to get an email when it finishes. I set up a script to send the email, and I figured I can just set `parallel` to 1 and then make the notification the next place in the queue. Unfortunately, I put the btrfs job in the default group and I don't want my default group set to 1 parallel job. 

**Describe the solution you'd like**
I'd like to create a new group 'btrfs' and move the btrfs job to it, so that I can set it to 1 parallel job for just that group.

**Describe alternatives you've considered**
I can monitor the status of the job using a script that loops and checks either `pueue status` or `btrfs balance status`, but that is more work. It would be much simpler to just leverage pueue for this, and I'm sure there are other cases where this would be useful.

**Additional context**
I'd be interested in implementing this feature if you approve it. I don't like wasting my time on PRs that get ignored by maintainers.

Thank you for creating such a cool tool.

**Comment by Nukesor** [comment]
Hi :)

Well, this feature request seems reasonable.

Moving tasks between groups, shouldn't be hard as long as they haven't been started yet.
However, once they have been started, this get's tricky.
Pueue has an internal "worker pool" representation since 1.0.0, which is based on groups.
There'll probably be a few weird edge-cases that need to be checked, and we have to properly test this. But it should be doable :)

**Comment by Nukesor** [comment]
PR's are welcome, feel free to work on this issue!

**Comment by Nukesor** [comment]
I'll close this issue for now, until somebody comes up with a proper usecase again ;)
