### ISSUE TITLE
Extract group config to separate file

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#240]
Pueue allows to set sevaral configs via cli AND config file. Specifically
- Groups
- The amount of parallel tasks per group

As a result, Pueue will go ahead and update the configuration file during runtime, whenever the user decides to adjust some group configuration.

To prevent any changes on the config file, we have to move everything that's dynamic to a separate config.
This config can be a simple `.toml` file and should contain a warning, that this will change during daemon runtime.

While we're at it, the current group state should also be extracted from the `State` struct and added to this file.
That way, we have a single persistant struct/file, representing the current state of Pueue's groups.

Help is very much appreciated, as I probably won't do this myself.

**Comment by loewenheim** [comment]
I've started working on this, primarily because I want to configure `pueue` via NixOS and that's only going to work if the config is feasibly immutable. My approach right now is to remove `groups` from the daemon settings and change `State.groups` to a `HashMap<str, (usize, GroupStatus)>`. As far as I can tell this would take care of saving the current group configuration because `State` is automatically saved; do I have that right? As a side benefit, it also cuts down on having to synchronize the group maps in `Setting` and `State`. However, this solution is probably not optimal if being able to edit the groups in a file is a design goal, but it seems that isn't really intended anyway. What do you think?

As a side note, it seems to me that the `default_parallel_tasks` setting is actually never used to create new groups, they're always created with a value of 1. Is that a bug or am I misunderstanding something?

**Comment by Nukesor** [comment]
Regarding `default_parallel_tasks`, you seem to be right. This config probably got lost during some refactoring. Thinking about it, it should probably be fine to drop this.

Your current approach is pretty much the same I imagined, so this sounds good to me :)

You're correct, the `State.groups` would be serialized and restored, when writing the state to disk.
I'm still considering, whether it would be a better solution to write `groups` to a dedicated file.
The main motivation behind doing so, would be to prevent group configuration loss in case the `state` get's corrupted for some reason.
On the other hand, having everything in a single file, which isn't designed for manual manipulation would be quite convenient.

I'm still undecided regarding that question.

The main problem I see with this feature, is backward compatibility for old configs.
I.e. old settings should still be parsed, i.e. the `settings.daemon.groups` `BTreeMap<..>` should become a `Option<BTreeMap<..>>` and on state load, any old groups from the config will be merged into the current `State.groups` field.
If the `settings.daemon.groups` field is found, a deprecation warning should be shown, which states that groups can be re-added by the config, even if they have been deleted in a previous session.
I.e.:

1. `pueued` starts, and loads groups `cpu` and `gpu` from config.
2. User deletes group `cpu`, but config doesn't get updated, as it'll soon be immutable
3. `pueued` get's restarted and group `cpu` get's added again.

This will definitely lead to some confusion.

**Comment by loewenheim** [comment]
> Regarding default_parallel_tasks, you seem to be right. This config probably got lost during some refactoring. Thinking about it, it should probably be fine to just drop this.
Starting groups with a default of 1 is totally reasonable and probably even safer than a global default.

Then I might actually do that first as its own PR. 👍

**Comment by loewenheim** [comment]
> If the settings.daemon.groups field is found, a deprecation warning should be shown

How should we do this warning? `println!`, `error!`, something else?

**Comment by Nukesor** [comment]
1. I like the idea of the `--parallel/-p` flag on the `pueue group` command. It sounds quite convenient :)
2. `error!` would be the way to go.
    `println!` is only used in critical (e.g. panic) environments or in the client, when we're printing normal output.

The next development cycle of pueue itself is done on the v1.1.0 branch. This branch uses the `pueue-lib` master branch until it's released, which makes it easy to develop both hand in hand.
Just make sure that your `pueue` PR's are branch of `v1.1.0` and are merged into `v1.1.0` as well :)
