### ISSUE TITLE
[Linux] Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#243]
I have noticed that pueued places its socket in `~/.local/share/pueue`, though I'm not sure whether that is the best option.  I have had one issue where the socket was left after an unclean shutdown, and the new instance was unable to create a new socket.

In general though, Linux environment include the `$XDG_RUNTIME_DIR` environment variable which "defines the base directory relative to which user-specific non-essential runtime files and other file objects (such as sockets, named pipes, ...) should be stored."  (See the [specs here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)).  This is typically stored in `/run/user/$UID` which is temporary only and a reboot clears out all the files.

I have thought about specifying the path in the configuration; however the path of `$XDG_RUNTIME_DIR` in my case changes at every boot as the UID is dynamically set by `systemd-homed`.

I would be happy to look at making a PR if needed.

**Comment by Nukesor** [comment]
Hm.
Regarding the first issue of `pueued` not being able to boot due to an existing unix socket file:
Do you still have logs for this?
I actually did quite a lot of work on properly handling this, which is why this surprises me. The current workflow looks like this:

1. Check if PID file exists. If process with PID is still running, abort boot.
2. Check if Unix file exists. If that's the case, check if we can do a full client connect, including secret exchange.
     -> If this succeeds, a fully operational daemon instance is obviously still running.
     -> If this fails, we assume the previous daemon was killed during cleanup. We remove the old unix socket and create a new one.
     
The scenario described by you really shouldn't be possible any longer since v1.0.


Regardingi the `$XDG_RUNTIME_DIR`
I would be fine with supporting the XDG standard, even though I'm not exactly sure of what's the beset way to handle configuration precedence.

For instance, I'm hosting two `pueued` instances on my server's user. One of them is used for local stuff, the other one is used by my external machines. The communication happens via ssh unix-socket-forwarding.
As a result, I have to keep the possibility of explicitely specifying a unix socket path, even though the $XDG_RUNTIME_DIR environment variable might be set.

It would also be quite confusing to have the `unix_socket_path` default to some value (i.e. ~/.local/share/pueue/`), which is then silently overwritten by environment variables.
Maybe some configuration flag, which let's users opt-in to use the XDG directory spec?

How do other programs implement this? I assume this project isn't the only one with this kind of requirements.

PS: Dynamically adjusting the configuration file shouldn't be a possible solution. This might be prohibited in a future release due to #241.

**Comment by JP-Ellis** [comment]
Regarding the boot issue, I unfortunately don't have the logs for that incident.  I don't remember the exact circumstances around `pueued` crashing, but I believe it required me to reset the computer.  Is it possible that the PID file still exists and another process has the same PID after the reboot?  It also might be related to a failure with `fscrypt` related to the hard reset.  If it happens again I'll make sure to get logs related to it.

With regards to multiple sockets, I can imaging a few cases and this is how I would think about it:

- For a system-wide daemon, the socket should be located at `/run/pueued.socket` or `/run/pueued/main.socket`.  This would be in analogy to `/run/dbus/system_bus_socket` for example.  As this isn't attached to a user, I don't think `$XDG_RUNTIME_DIR` is well defined so that makes the most sense.  Note that I don't know if a system-wide daemon is adviseable as it could run into issues with permissions / privileges (unless the task is run using the UID of the person who submitted the task?  But then how is that verified?)
- For user-specific daemons, the socket should be located at `$XDG_RUNTIME_DIR/pueued.socket`. This would be in analogy to `$XDG_RUNTIME_DIR/bus`.  As each user should have their own runtime directory, there is no issue with different users running their own `pueued` daemon.
- In all cases, a socket path can specified manually which will always take precedence.  This would allow for example for multiple system-wide or user daemons to run without impacting each other.

One thing I guess I don't really understand why there would be a need to a user to run multiple `pueued` daemons on a single machine as the ability to set multiple groups I believe should be enough?

I do understand the case of having the client talk to multiple daemons (especially if it happens via a ssh socket forwarding).  Would it not be easier in that case to add a flag the to client to allow for a socket / address:port to be specified?

**Comment by Nukesor** [comment]
1. I wouldn't take the scenario of a system wide user into account. This isn't what Pueue has been designed for and it's really not advisable. I'm not even sure if it's possible, as the processes still need to be executed with a shell. I guess on a system process, this would default to `root`?

- The case of multiple daemons under a single user is definitely a convenience thing.
   That way the tasks I run as a remote user and the tasks as the local user (which are of completely different nature) don't end up in the same queue. Working with groups would work, but sometimes I'm a lazy person ;D.

- The flag is a valid point and it already exists, but you also have to point to the correct secret that's used by the remote daemon.
    You also need other configurations, as you have to tell the client to not use local logs, but rather stream them from a remote daemon. This is something the client cannot know by simply looking at a unix socket.
    Doing all of this with commandline options and an alias is kind of cumbersome and would really bloat the CLI interface.
    Using a config is definitely advised.


I guess, we could make most of the configuration paths `Option`al.
If they are `None`, `pueued` and `pueue` check for the respective `XDG` path for each path.

In case the `$XDG_*` environment variables cannot be found, we have to crash hard with a proper error message.

This logic should be moved to the platform specific code, as XDG paths probably won't exist in MacOS code and definitely won't exist or at least be different on Windows.

**Comment by JP-Ellis** [comment]
Good to hear that the system-wide daemon need not be taken into account.  I think it would be possible to run it as root and then use some sort of `su` to run each task as different users, but I feel like that's a can of (very ugly) worms which shouldn't be opened if there's an alternative (e.g. each use has their own daemon).

I agree that most of the configuration paths should probably be optional, and the case where `$XDG` environment variables are unavailable should be rare (and presumably the user should know why the `$XDG` environment variables are not defined as this seems highly non-standard).  I agree that other operating systems will follow different conventions and it might be worth investigating how MacOS handles sockets.  As for Windows, I'm guessing they don't have sockets at all?  Though I really don't know.

And perfectly good point regarding the command line flags.  They may not be the best way, and pointing to different configs might be best.  In fact, as an alternative to switching between configs, could it be worth having separate profiles within the one configuration file?  This could be done in a way that is backwards compatible if the schema for the config was changed from:

```yml
client:
  # ...
daemon:
  # ...
shared:
  # ...
```

to:

```yml
client:
  # ...
daemon:
  # ...
shared:
  # ...

remote:
  client:
    # ...
  daemon:
    # ...
  shared:
    # ...

other_profile:
  # as above
```

The `default` profile we refer to the one that isn't named, and users could specify as many profiles as they want as long as it was not called `client`, `daemon` or `shared`.  A command line flag `--profile x` would allow one to easily switch between each.

**Comment by Nukesor** [comment]
1. We should definitely consider and handle the case, that the XDG variables aren't there.
I don't want to enforce this standard, I rather want to support it in a non-obtrusive way.

For example:
- I'm running a rather bare metal i3 setup and I had to set the XDG variables by hand in my shell environment file^^.
- You also cannot expect the XDG spec to be enforced on servers as well.
    Especially on servers that aren't controlled by you, such as university and client servers or high performance clusters.

Pueue should still perform perfectly fine in these environments.


2. Maybe, we could take a look at the environment, when we start up for the very first time?
If all required environment variables are there, we just set them to `null`(`~`).
If they aren't, we populate them with the default values?

Anyhow, this would still be confusing if they aren't there on first start, but are added later on.
Would we still use the XDG variables in that case? This could be very confusing.

I also imagine it to be confusing, if there are `null` values in your config.
If you don't know about the XDG standard, which quite a few people probably don't, you'll probably wonder where your files are...

3. Windows doesn't have unix sockets, but they have conventions for the other paths as well.
If we start to support the XDG spec, we have to do it in it's entirety. I.e. `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME`.

4. Regarding the structure of different profiles.
The profiles should probably be located in one parent key:
```
client:
    # ...
daemon:
    # ...
shared:
    # ...
profiles:
    remote:
        client:
            # ...
        daemon:
            # ...
        shared:
            # ...
    other_remote:
        client:
            # ...
        daemon:
            # ...
        shared:
            # ...
```
That way implementing and verifying the config is much easier.


Anyhow, I have to think about this for some time. It feels like we need to think this through more :D.  But that could also be because I just woke up ;).

**Comment by JP-Ellis** [comment]
I don't know of many circumstances where the XDG environment variables would not be defined.  From what I understand, they are [set by `pam_systemd`](https://www.freedesktop.org/software/systemd/man/pam_systemd.html) which I thought handled all logins (except maybe root)?  This should apply to all servers too (I just checked all servers I have access to, and they all define at least the minimally required XDG variables).  How did you manage authentication in that barebones setup?  And did you only have to define those XDG environment variables which are optional, or did you have to specify all of them?

The XDG specification is clear that in the case of a missing environment variables a predefined default value should be used, so I think it would be safe to use that as a fallback.  I agree that if you went from an environment where this wasn't defined to one where it is defined and has a non-default definition, things would break -- but so would nearly all other programs.  I don't think that such a scenario needs to be nicely handled by pueue as I seriously doubt  this is handled nicely by any other program.

The only caveat to the above defaults is `XDG_RUNTIME_DIR` which, from what I can see, has no default fallback.  The specification does clarify what ought to happen in the case where it is not defined:

> If `$XDG_RUNTIME_DIR` is not set applications should fall back to a replacement directory with similar capabilities and print a warning message. Applications should use this directory for communication and synchronization purposes and should not place larger files in it, since it might reside in runtime memory and cannot necessarily be swapped out to disk. 

The 'similar capabilities' I presume refer to the fact that the runtime directory should not be persistent.  Perhaps defaulting to `$TMPDIR/pueue/main.socket` should work?  This also resolves the issue of what happens if pueue was launched in an environment where the runtime directory was not defined, to one where it is defined: pueue would just use the new runtime directory for the socket and the old one in `$TMPDIR` should be cleared up automatically by the system.  I also tried to look for what happens in XDG_RUNTIME_DIR is not defined with other programs, and according to Google a lot of applications outright break.

Lastly, I agree that if pueue starts using `$XDG_RUNTIME_DIR`, it ought to follow all of them.  I doubt this would be a big issue as the defaults are already beiung used (`$HOME/.local/config` is the default for `$XDG_CONFIG_HOME` and `$HOME/.local/share` is the default for `$XDG_DATA_HOME`).

I'm not going to comment much on the MacOS / Windows situation as I really don't know how they are meant to work.  I think it would be fine to keep the scope of this issue to using the XDG specification.  I'm going to create a new issue where we can discuss the implementation of profiles.

**Comment by Nukesor** [comment]
There are only a few XDG variables managed by pam_systemd.

Specifically $XDG_CONFIG_HOME and $XDG_DATA_HOME aren't set by default.
They're rather set by desktop managers, which quite a few people (including me) don't use.
Naturally desktop managers also don't exist on servers.

I see how the comment above can be confusing, as I didn't have to set all variables myself :D
This is my current setup in my .zshenv

```
# XDG Setup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
```

But I stumbled upon those missing at more than on occasion on other systems.

**Comment by Nukesor** [comment]
I would really like to get this done soon.
We'll probably have to remove the `config-rs` dependency, as it's already kind of wonky to specify defaults with it and more complex logic will probably not be implementable with it. Or at least not ergonomically.

Here are two flowcharts/diagrams on how config variables should be read and which configs take precedence.

Config precendence graph:
![Untitled Diagram drawio](https://user-images.githubusercontent.com/3322822/143922486-5812619d-2891-4878-8adc-79f07c5f81c1.png)

Initial configuration file precedence graph. This is how the values of the config that will be created on first start are determined:
![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/3322822/143922585-f5a668e4-b4bb-4532-b540-cc97cda45d9b.png)

As your initial requirement was that the socket should be moved to the XDG runtime directory, we also have to add a new configuration variable, specifically the `--runtime-dir` flag.

`pueued` and `pueue` use the `settings.shared.pueue_directory` for now.
This directory however needs to be persistent, for the state and logs being persistent between boots. This is exactly what the `$XDG_RUNTIME_DIR` is **not** designed for.

I guess this will result in a rewrite of the larger part of pueue's configuration code.
