### ISSUE TITLE
UX: make it more obvious that group is paused after `pueue kill -g` and tasks are scheduled as paused

### ISSUE THREAD

**Issue by d33tah** [Nukesor/pueue#265]
**Is your feature request related to a problem? Please describe.**

I recently needed to do `pueue kill -g xargs -c`. I was later surprised to see that newly added tasks aren't executed like they normally wood.

**Describe the solution you'd like**

After running `pueue kill -g`, print to the stderr that a group is paused. This is not necessarily an obvious consequence of `pueue kill` - note that e.g. Unix's `kill` doesn't also suspend the parent of the killed process, so I'm not exactly sure where how this behavior was inspired.

Also, it would be a good idea to warn the user that the group is paused if tasks are added to a paused group. Ideally, in a separate line and a different color so that it's more difficult to miss.

**Describe alternatives you've considered**

1. don't pause groups by default
    * breaks backward compatibility
2. add a way to override auto-pausing

**Additional context**

Tested under Pueue client 1.0.3, installed from cargo sometime last week.

**Comment by Nukesor** [comment]
The idea behind this was, that one often doesn't want any follow-up tasks to start, if all tasks in a whole group is killed.

Most of the time, a group is killed because something went wrong or a mistake has been made. By pausing execution of further tasks, further malicious commands won't be executed. It might be unintuitive, but it's also the solution that breaks less things.

I agree that we can have an option to permanently override this behavior.

**Comment by Nukesor** [comment]
https://github.com/Nukesor/pueue/pull/280

This implements your initial proposal for better output in both cases:
- When killing whole groups
- When adding tasks to paused groups.

The different color is a little tricky, as the message comes from the daemon, but the styling can only be done by the client.
There currently exists no mechanism for such behavior.
