### ISSUE TITLE
[BUG] Io Error on startup

### ISSUE THREAD

**Issue by EntilZha** [Nukesor/pueue#293]
#### Describe the bug

I run the command and get an Io error, like below:

```
$ pueued
Error: Io Error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```
Running on verbose doesn't seem to help, version is 2.0.0 installed via cargo

#### Steps to reproduce the bug

1. Run `pueued`
2. Observe the Io Error

#### Expected behavior

Pueue should have started in the background

#### Additional context

- OS: Ubuntu Linux 18.04

My best guess is that pueue is making use of a directory/port/file that I don't have read/write access to. Any ideas?

**Comment by Nukesor** [comment]
Could you run `pueued` with the verbose flags `-vvv`?

This should give us some more information.

**Comment by Nukesor** [comment]
You can get that version directly via cargo install with this command:
`cargo install --git https://github.com/Nukesor/pueue.git -f`

**Comment by Nukesor** [comment]
Ping @EntilZha  
Would love to get this fixed before other people run into it :slightly_smiling_face:

**Comment by EntilZha** [comment]
I updated to the git version and then ran/got this:
```
$ pueued -vvv
16:48:26 [INFO] Parsing config files
16:48:26 [INFO] Checking path: "/data/home/entilzha/.config/pueue/pueue.yml"
16:48:26 [INFO] Found config file at: "/data/home/entilzha/.config/pueue/pueue.yml"
16:48:26 [INFO] Start restoring state
16:48:26 [DEBUG] (1) pueue_daemon_lib::state_helper: State saved at: "/data/home/entilzha/.local/share/pueue/state.json"
Error: Io Error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```
So unfortunately still not clear what error is causing this I think

**Comment by Nukesor** [comment]
Thanks! This already helps a lot.

I assumed that this error occured due to the new XDG support for config and cache files, but this doesn't seem to be the case. The daemon manages to create all needed directories, to read the config files and to restore & save the state.
This means that the error probably originates from the networking/unix socket logic or from the log file handling inside the TaskHandler.

I suspect some error in the unix socket handling logic due to the new XDG support for `$XDG_RUNTIME_DIR`.

I also added another bunch of error display optimizations with proper paths for path related IO errors, which sadly isn't the default in std's IoError (yet).
You can get them like this:
```
cargo install --git 'https://github.com/Nukesor/pueue.git' --branch better-io-errors
```

You could also check whether using tcp works by setting `use_unix_socket: false` in your `pueue.yml`.
If that's the case, try to check whether `$XDG_RUNTIME_DIR` is set and whether the path actually exists.

**Comment by Nukesor** [comment]
Ping @EntilZha
This should be the last time you have to check how this works :)
You should now get a proper error message with the correct context and the exact missing path or directory.

**Comment by Nukesor** [comment]
I would love to get this resolved, since I'm planning to release a 2.0.1 patch release soon.

**Comment by EntilZha** [comment]
Sorry, been busy, but did get a chance to rerun and have this:
```
$ pueued -vvv
21:34:10 [INFO] Parsing config files
21:34:10 [INFO] Checking path: "/data/home/par/.config/pueue/pueue.yml"
21:34:10 [INFO] Found config file at: "/data/home/par/.config/pueue/pueue.yml"
21:34:10 [INFO] Start restoring state
21:34:10 [DEBUG] (1) pueue_daemon_lib::state_helper: State saved at: "/data/home/par/.local/share/pueue/state.json"
Error: I/O error at path "/run/user/2482/pueue_par.socket" while creating unix socket:
No such file or directory (os error 2)
```
Checking directories, looks like `/run/user` exists but `2482` does not which is my user id.

**Comment by Nukesor** [comment]
No worries. Thanks for the swift reply :)

This is rather odd.
Could you check what your `echo $XDG_RUNTIME_DIR` looks like?
It seems that your XDG variables are somewhat misconfigured.

Maybe your desktop manager is started as a different user or something alike?

Anyhow. To fix the issue at hand
- Make sure that the `$XDG_RUNTIME_DIR` points to the correct runtime directory. 
This could otherwise result in errors for other programs that respect the XDG standard as well.
- Or simply set your runtime directory to something different. I would recommend to use the `pueue_directory`, which was the default in Version 1:

`~/.config/pueue/pueue.yml`:
```
shared:
  runtime_directory: "~/.local/share/pueue"
```

**Comment by EntilZha** [comment]
Looks like `echo $XDG_RUNTIME_DIR` points to `/run/user/2482`, which would explain the prior error. In this case, I am running `pueue` on a shared slurm cluster so there isn't a desktop manager (only ssh).

I'll give both solutions a try.

**Comment by Nukesor** [comment]
Perfect, I'll go ahead and close this issue, as this is mostly an issue with the system surrounding Pueue :) 

Anyhow, thanks for the bug report! The error reporting for these kind of errors is now way better than before.
Other people that run into this problem now get a proper hint on what might be wrong.
