### ISSUE TITLE
Option to read the command to be executed from stdin?

### ISSUE THREAD

**Issue by johann-petrak** [Nukesor/pueue#294]
With more complex commands to be executed, which contain spaces, characters that need escaping, piping etc, passing these on as arguments becomes very complex, unintuitive and annoying. 

So, why not have some option which will, instead of parsing arguments after "--", read one or more lines from standard input, concatenate them into a single command line and execute that?

**Comment by Nukesor** [comment]
I guess this is a reasonable, but we cannot simply concatenate multiple lines.

Pueue accepts any valid bash as input and since newlines have some meaning in bash, this would utterly break.

E.g.

```sh
while true; do
    echo "test"
    mkdir tmp/some_path
    sleep 1
done
```

Would be converted to
```sh
while true; do    echo "test"     mkdir tmp/some_path    sleep 1 done
```
which obviously doesn't work.


One thing we should investigate is whether clap has official support for this already.
I don't want to loose the CLI parsing error message if no stdin is provided.

**Comment by Nukesor** [comment]
@johann-petrak Would you be willing to investigate how well this works in conjunction with clapv3?

**Comment by Nukesor** [comment]
Closed due to inactivity :)

If anyone else is interested in investigating and building this, feel free top re-open the issue!
