### ISSUE TITLE
Problem starting daemon

### ISSUE THREAD

**Issue by avernan** [Nukesor/pueue#30]
When I try to start pueue's daemon I get the following error
```
$ pueue --daemon
usage: pueue [-h] [--daemon] [--no-daemon] [--stop-daemon] [--root ROOT]
             {status,config,show,log,add,remove,switch,send,reset,clean,pause,start,restart,kill,stop}
             ...
pueue: error: too few arguments
```
I have the same outcome by running it as `--no-daemon`.

The installation was done with pip and without sudo, as follows
```
pip install --user pueue
```

Let me know if there are other relevant information I can provide.

**Comment by Nukesor** [comment]
I just did a clean install with `pip install --user pueue`, but I can't recreate your case. It works with `--daemon`, `--stop-daemon` and `--no-daemon` for me.
I suppose you use python3 pip for installation, as you would've probably gotten an instant stacktrace otherwise.
Is there anything else you did? Does it work without `--user`?

**Comment by avernan** [comment]
Apparently my system only has python2-pip installed. I tried uninstalling and installing again and now I get a stacktrace when I try to launch pueue.

I suppose pueue is for python3 only? I was naively expecting pip to only be able to install compatible packages.

**Comment by Nukesor** [comment]
Sorry about that :/ .I decided to not support pueue with python2, as there are more and more frameworks/distributions which drop python2 support.
But there should be a python3 package with pip3 for all major Linux distributions anyway.
Python2 and Python3 can exist side by side without any problems!
