### ISSUE TITLE
Add an option to reverse status output

### ISSUE THREAD

**Issue by farid-fari** [Nukesor/pueue#301]
Add a `-r` option to `pueue status` so that the tasks are outputted in descending number rather than the usual ascending output. Useful in cases where there are many tasks and you want to see how far along the queue the execution has gone.

**Comment by Nukesor** [comment]
Hm. My initial thought was to use the `format-status` command, but the output of that command is always put back into a BTree, which is then ordered as usual.

It's probably a good idea to work with Vectors instead of BTrees in the display stage.

This would allow arbitrary ordering in the spirit of #213 

A simple reverse alias would then look like this:
`alias pr="pueue status --json | jq -c '.tasks | [.[]] | reverse' | pueue format-status"`

**Comment by Nukesor** [comment]
I'll check if we can easily refactor the current display logic in the next few days :)

**Comment by Nukesor** [comment]
The linked PR now makes `format-status` respect the order in which tasks are provided.

This should work until proper query support is added :)
