### ISSUE TITLE
[BUG] Missing Documentation on communicating with the daemon

### ISSUE THREAD

**Issue by stranger-danger-zamu** [Nukesor/pueue#308]
#### Describe the bug

There is no documentation on _what_ to send to communicate with the pueue daemon. Looking at the code, I can see it's (probably) a Unix Domain Socket talking SOCK_STREAM, but beyond that it's not really clear. 

#### Steps to reproduce the bug

1. Look for documentation on the socket protocol.
2. Find none.

#### Expected behavior

Have a clear description of what to send over the socket. 

#### Logs/Output

I know I'm doing something wrong while trying to follow the pueue client code since after every request I'm getting a memory allocation error and having the OS OOM kill it. 

``` log
Apr 09 22:57:11 srv1 pueued[1149133]: memory allocation of 144117387132666368 bytes failed
```

#### Additional context

- OS: Fedora 35
- Pueue version: 2.0.2

* I know that I should be sending a vector of bytes to represent a u64 int and then the message, but no matter what I do, it seems to try to allocate TiB of memory and get killed. 
* Due to the fact that serde is handling the serialization, there is no clear hint as to the encoding of the payload itself. 
* Is it that the unix socket is encrypted and I need to run TLS?

**Comment by Nukesor** [comment]
Right now, there are no docs for the API, since the API is designed to be used with `pueue_lib`.

You can of course re-implement the protocol in other languages.

**Sockets:**

- Unix sockets are unencrypted
- TCP sockets are encrypted via TLS

**Communication:** 

Sending and receiving bytes is handled via the `send_bytes` and `receive_bytes` functions from `pueue_lib`. There're also the convenience functions `send_message` and `receive_message`, which automatically handle serialization and deserialization for you.

The payloads itself are defined via the `Message` enum that can be found in `pueue_lib` `src/network/message.rs`

The serialization/deserialization format is `cbor`.

**The Protocol**

Before communication starts, a simple handshake + authorization is done by the client and daemon. This can be found in the `client/client.rs` `new` function.

The following is written from the client's perspective:

- Connect to socket
- Send secret bytes
- Receive the daemon's version, which is sent as a successful response
- Send message
- Receive message

Depending on the type of message, the socket might be instantly closed by the daemon after receiving the message.

For instance, querying the `status` is just a simple ping-pong, which requires no further communication.

`follow` on the other hand will result in the daemon continously sending new messages with the new log output.

**Comment by Nukesor** [comment]
@stranger-danger-zamu I'm curious. What exactly are you trying to accomplish? Do you try to interface with `pueued` via a non-Rust language?

I might go ahead and add more docs on the exact flow of the protocol in the future, but I would really like to hear a few use-cases.

**Comment by Nukesor** [comment]
I also just added a description on how send/receive_bytes works to my first answer.

**Comment by Nukesor** [comment]
More detailed docs have been added in 68ca577

**Comment by stranger-danger-zamu** [comment]
Awesome! This was exactly what I needed.

As for use cases, I'm interfacing pueue with a number of services running on the local machine written in different languages (predominantly python, but there are others). 

For a more concrete use case, I have a flask server which blocks when running one-shot tasks like generating missing thumbnails when first requested. Its performance is fine for the number of users it has (ie. waiting up to 300ms is fine since it has less than a dozen concurrent users).

However there are other things like this that'd be great to do that can run much longer (eg. calling `gallery-dl`, `yt-dlp`, or `ffmpeg`). So instead of implementing a comparable feature set, I'd rather just leverage pueue for monitoring the tasks.

**Comment by Nukesor** [comment]
Interesting :D 
Thanks for the detailed description!

I'll close this issue for now. Feel free to re-open if any further questions come up.

**Comment by GhisF** [comment]
Hi,

You mentioned the `pueue_lib` in order to communicate with the pueue daemon, is it possible to get some documentation or a basic example that explains how to use this lib to connect and interact with the daemon (put commands in queue, get the status of a tasks...).

We use pueue to collect and run stages of genetic data processing pipelines on our servers. The workflow manager is currently written in go and communicates with pueue using os/exec to run the pueue client as an external command.
I'm considering rewriting it in Rust, and I guess it might be worth using `pueue_lib` to communicate directly with pueue daemons.

Thanks.

**Comment by Nukesor** [comment]
You should find everything you need the pueue_lib::network docs :)

https://docs.rs/pueue-lib/0.20.0/pueue_lib/network/index.html

>Before the real data exchange starts, a simple handshake + authorization is done by the client and daemon. An example on how to do this can be found in the pueue’s crate::client::Client::new() function.

**Comment by Nukesor** [comment]
You should be able to communicate with the daemon with Go as well :)
You would just have to re-implement the protocol, which probably shouldn't be too hard. I tried to document the networking/protocol code as good as possible.
