### ISSUE TITLE
Can paths in configuration files be relative to configuration directory?

### ISSUE THREAD

**Issue by tjni** [Nukesor/pueue#309]
To start, thank you so much for this tool! I'm not sure this is the intended purpose, but I am going to try to use it as a lightweight, cross-platform service manager.

#### Is your feature request related to a problem?

For isolation, I want to configure the data and runtime directories to be relative to the root directory of my project, which is also where my pueue config file lives. Therefore, I use relative paths in the config file for both of those directory settings. I also run pueue from subdirectories (which contain individual services). When I do that, I supply a different relative path to the config file, but the application breaks because it reads in the directory settings relative to the directory in which I've run the program.

#### Describe the solution you'd like

I think that it makes sense for relative paths in the config file to be relative to the location of the config file.

#### Additional context

I'm open to other solutions too and willing to help implement whatever is decided upon.

**Comment by Nukesor** [comment]
Hi :)

As far as I know the paths are not relative to the configuration file, but rather to the working directory of the daemon/client. But to be honest, I never used it that way and it wasn't intended to be used that way until now :D.
I'm also curious about the current behavior with relative paths, please tell me whether my initial assumption was correct :). 

Regarding the intended purpose of your usecase:
Your scenario is definitely not part of the [design goals](https://github.com/Nukesor/pueue#design-goals) of Pueue, as it's designed as a single-user commandline helper and not as a full-featured service manager for parts of some infrastructure.

It might work, but features that improve such a use-case won't be added, as this is better suited for another more specialized tool.

**Comment by tjni** [comment]
Thank you for such a fast and thoughtful response.

In response to the question about how the paths behave, they _are_ indeed relative to the working directory, and this is the part I'm stumbling over.

My thought process about this is: let's take as given that it's useful to allow different locations of the config file – that feature exists currently at least. Then, there are two ergonomic issues that I've encountered with a custom location.

1. Each invocation of pueue must specify a path to this config file, which is slow and error prone for a human to do. This pain point can be managed without any changes to pueue by automation or helper scripts. In practice, I've seen some tools make this easier for users by resolving config files from parent directories, which is a common use case.

2. If the paths in the config file themselves are relative, then pueue must be executed always from the same directory, even if groups or tasks are organized in subdirectories. This can be managed by _not_ using relative paths, i.e. by using a fixed path from the user's home directory, though the looser file system isolation makes this less ideal for some infrastructure.

After reflecting, it does seem like solving this is counter to the goals you've laid out for the project, so I'll close this ticket. If you do know of another lightweight, cross-platform tool better suited for this use case, let me know. Thank you for your time!

**Comment by Nukesor** [comment]
Regarding your pain points.

1. This is true, I used to have an alias for this exact reason which then points to a specific config file. Since the introduction of configuration profiles, I switched to an alias that simply calls the config with the given profile. I'm not exactly sure what you mean with "resolving config files form parent directories" though. Do those programs search parent directories for a config file with a specific name?
2. I agree that configuration paths that depend on the place of execution are rather confusing.
    IMO it would be ok to change this behavior and make relative paths in the configuration file actually relative to the configuration file. Let's re-open this issue for the purpose of this chnage :)  
   

I often thought about writing such a tool myself, but I didn't have the need for it yet.
It would definitely be a super cool project with many interesting challenges.

I also thought a lot about integrating such features in Pueue, but it just wasn't designed this way and it would need a major redesign and many changes in behavior. It will be much cleaner and most importantly much more maintainable to keep this separate for each specialized use-case.

**Comment by tjni** [comment]
>  I'm not exactly sure what you mean with "resolving config files form parent directories" though. Do those programs search parent directories for a config file with a specific name?

Yup, that's right. For example, this is what [just](https://github.com/casey/just) does, it's similar to [what git does](https://git-scm.com/docs/git-config/2.30.3#FILES), and it's part of [eslint's configuration strategy](https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy). This way, one can usually depend on the tool to do the thing it's configured to do in each directory it's invoked.

> I often thought about writing such a tool myself, but I didn't have the need for it yet.
It would definitely be a super cool project with many interesting challenges.

It's something I've thought about too, but I'm sure that, for you too, it's hard to find the time. I totally agree that adding those features would be a challenge both to design and to maintain.

> IMO it would be ok to change this behavior and make relative paths in the configuration file actually relative to the configuration file.

I would be happy to try to make this change. Please bear with me cause I'm still relatively new to Rust. (Professionally, I have mostly used front-end technologies and Java.)

One thing that I noticed already and can use your opinion on is how to enhance the `pueue_directory()` method to make use of the config directory. It is on a nested struct named `Shared`, which only contains configuration so far. One way could be to add a field to the struct that's ignored by `serde`, though that doesn't feel explicit. On the other hand, I can't think of a way to pass this extra information through all of the current layers explicitly without creating either a lot of wrapper structs or changing a lot of method signatures.

**Comment by Nukesor** [comment]
I agree that this is somewhat tricky.

Until now, the config path has only ever be used at the very beginning of the program, to read the config.

I also agree with your possible solutions:

1. Pass the config parent directory to all functions that return another path from the `Shared` struct.
    This will be a huge breaking change in our API.
2. Add an optional field to the settings struct.
    This would then be ignored when deserializing and set once it has been deserialized.
    I really don't like this solution, as we would misuse the the configuration structs to store a runtime variable and we would probably use `unwrap()` on this field everywhere which isn't very clean either.
    
My proposal would be to combine the first solution with write a simple wrapper struct around `Settings`.

```rust
pub struct AppSettings { // This is just a placeholder name :D
    config_dir: PathBuf,
    settings: Settings,
}
```

We could then move the functions from the current `impl Shared` to that struct.
This would change quite a bit of code, but the API that's lateron used would be basically the same. Though it would then be called from the root struct instead of the `Shared` struct.

`AppSettings` could also implement `deref`, so one could easily access the inner `settings` field.

However, the main problem I see with this is, that this is an actual breaking change in the actual communcication API. This would, for instance, break the `status` command, since the settings are part of the state.

**Comment by Nukesor** [comment]
While we're at it, we should also consider using the `dirs` library, which ships with full XDG support and other best practices for configuration/data/runtime directories on various plattforms.

The current XDG and cross-plattform path handling is rather crude and this will save us quite a bit of plattform specific code and complexity.

However, this will need a major version update as well, as some paths might change due to this.

**Comment by tjni** [comment]
A runtime wrapper over `Settings` sounds good to me. To check my understanding:

1. This is a breaking change to the behavior if someone is already using relative directories and always runs `pueue` from a non-config-file directory. I think this is rare, but I don't mind upping the major version either.

2. The `status` command today echoes back a relative directory if one were provided. I don't think this has to change, unless we want to enhance the utility of it by returning a path relative to the current working directory or (better in my opinion if we go down this route) an absolute path.

**Comment by Nukesor** [comment]
1. This is also true, but it's something I would rather disregard as this isn't documented behavior and rather a bug than an actual feature that's going to be changed.

2. This is not about relative directories, but rather about the structure of the payload that's passed between the client and the daemon, i.e. the actual API.
    Pueue doesn't have a proper API versioning mechanism yet. Simple changes in the schemas are handled by `cbor` (removal/additions of fields).
    Changes in types however aren't and need either manual handling of versions (which we would need to introduce to the project) or a breaking change in the version.

To be more specific, the current State looks like this:
```
#[derive(PartialEq, Clone, Debug, Deserialize, Serialize)]
pub struct State {
    /// The current settings used by the daemon.
    pub settings: Settings,
    /// All tasks currently managed by the daemon.
    pub tasks: BTreeMap<usize, Task>,
    /// All groups with their current state a configuration.
    #[serde(deserialize_with = "deserialize_groups")]
    pub groups: BTreeMap<String, Group>,
    /// Used to store an configuration path that has been explicitely specified.
    /// Without this, the default config path will be used instead.
    pub config_path: Option<PathBuf>,
}
```

Funnily enough the `config_path` is somehow stlil in there even though it's no longer used in new versions. Technical debt is real.

The new structure would look like this:

```
#[derive(PartialEq, Clone, Debug, Deserialize, Serialize)]
pub struct State {
    /// The current settings used by the daemon.
    pub settings: SettingsWrapper,
    /// All tasks currently managed by the daemon.
    pub tasks: BTreeMap<usize, Task>,
    /// All groups with their current state a configuration.
    #[serde(deserialize_with = "deserialize_groups")]
    pub groups: BTreeMap<String, Group>,
}
```

with SettingsWrapper being:

```
pub struct SettingsWrapper { // Still a placeholder name
    config_dir: PathBuf,
    settings: Settings,
}
```

Any old daemon messages cannot easily be deserialized into the newly expected format, since there structure is simply different and there's missing data.

However, we might be able ignore failures and work with `Default`, which is implemented on `Settings` since v2, as a workaround.

After thinking about it, it might be a good idea to fully remove the settings from the state. This is a leftover from when groups where configured via the configuration file. I really don't see the need to keep it in there any longer...

**Comment by Nukesor** [comment]
To be honest, this is probably something that should be done by me.

There are a few architectural changes that need to be done in order to support this new structure.
I also don't see an easy way out for the deserialization problem.
The solution via `Default` doesn't work, as the binaries that're currently out there don't use the default `Settings` if they're missing in the payload. This will be a breaking change in any way, unless we do some API versioning.

The main reason I didn't introduce API versioning yet is, because it's hard to do properly, tricky to test and it's a huge maintenance overhead... 
Though after having another breaking API change shortly after releasing v2 really makes me overthink that decision. I need to think some more about how to handle changes like this.

**Comment by tjni** [comment]
Sounds good to me! I can work around this.

If it's too much effort, feel free to close this issue too; I wouldn't mind.

**Comment by Nukesor** [comment]
I finished the preparations for this issue (refactorings, cleanup and usage of `dirs`).

However, I still decided to not add this feature with Pueue's usecase in mind.


Pueue's main usecase and scope is to be a CLI helper tool running as a normal user on either a PC or a server.
As such, it can expect to use the user's configuration directory to be present and there shouldn't be a need for relative configuration paths.

I would have been ok with adding this change if it wouldn't require many changes.

As it currently stands, however, we would need to adjust many lines of code and quite a bit of logic, as well as introduce breaking API changes to implement this feature.
Hence, with Pueue's usecase in mind, this doesn't seem like a sensible change.

Anyhow, I still want to thank you for your proposal, as it triggered a few other improvements and cleanups in Pueue's codebase, which I'm very pleased with!
