### ISSUE TITLE
Option to define how many jobs a process occupies

### ISSUE THREAD

**Issue by IncredibleLaser** [Nukesor/pueue#325]
#### Is your feature request related to a problem?

Currently, it's only possible to define a fixed number of jobs to run in parallel, regardless of their actual resource usage. E.g. I have a processor with 24 logical cores and want to run a series of commands with varying amounts of threads used which are known before starting.

#### Describe the solution you'd like

I'd like to be able to define how many parallel jobs a single command occupies, e.g. run `pueue add -N 4 command` so that it consumes 4 jobs of my available pool.

#### Describe alternatives you've considered

Currently, I'm using task-spooler with the -N option.

**Comment by Nukesor** [comment]
I took some time to properly think about this.

The idea to have a token pool for each group and having each task consume an arbitrary amount of those tokens is kind of interesting. It also goes into the direction of complex scheduling, which is something I don't want for Pueue. There're already so many features and feature creep is a real problem.

So here's what's in my mind on what needs to be done, what would need to change and how this would affect Pueue:

- We would have to rename `parallel` to `tokens` or something alike, as this would otherwise be really confusing. I'm already not very happy with the naming.
   -> This would be a breaking change in our CLI
- We have to write proper docs, properly explaining this feature. Right now, the parallelism feature is really simple and intuitive, we would have to find a way to hide the new complexity for other users, as 99+% probably don't need and use it.
- We would have to add an additional field to `Task`, namely `tokens`.
- We have to adjust the logic for when new tasks can be spawned. This should be easy.
- We have to do some checks that users cannot queue tasks that need more tokens that're available in the group.
- How do we display it? Do we put in another optional `column` in the `pueue status` view? The table is getting pretty crowded...

I don't think that implementing this will be a big change, on the contrary it should be rather straight forward.

I'm mostly thinking on how to add this feature in an non-intrusive way.

**Comment by Nukesor** [comment]
Maybe, we could introduce `tokens` as an subcommand alias for now! This would make the transition phase a lot nicer.

Still thinking about proper wording on how to explain this.
We would also have to update the README gif :D

Do you by any chance know a good and convenience tool for that?

**Comment by Nukesor** [comment]
A few other things that need to be considered:

- We also have to do checks when changing the token size of a group. Otherwise there might be tasks in a group that cannot be executed.
- We probably have to add a new `edit` flag to edit the tokens of a job in the long run.
- Tasks will no longer be executed in their expected order. This might be a weird und unexpected side effect.
    E.g. if you have a queue of size 8, many tasks with requirements `2`,`1`,`3` and one job with `5`, that job will be executed last.
    
    This is a classic scheduling problem and I really don't want to add any logic that handles such edge-cases.

**Comment by IncredibleLaser** [comment]
Thanks for your reply. I also had similar thoughts about the order of command execution — I initially thought it'd not be an issue because pueue allows one to define dependencies so even if the job order might not be the same one as they were added, you wouldn't run into dependency issues.

But I agree that there shouldn't be any complicated logic to "handle" this kind of issue. Once this functionality is used, there's no longer a guarantee the order of commands is kept.

I fully understand if you don't implement the functionality, I'm aware of at least some of the implications.

**Comment by Nukesor** [comment]
After careful consideration, this doesn't fit into the scope of Pueue.
Pueue is still designed to be a convenience tool for server operators. A handy cli tool for day-to-day use.

This feature would introduce quite a bit of logic that would be part of a proper task scheduler, which Pueue was never intended to be.

Building a good scheduler takes a log of consideration, planning and work. To make it user-friendly, we would have to provide multiple scheduling algorithms for several use-cases, as well as very extensive documentation.

This is another feature that would be perfectly suited for a big brother of Pueue (which needs to be written yet).
