### ISSUE TITLE
Possible Pebcak - How can i extract the PID of a current running task.

### ISSUE THREAD

**Issue by getsec** [Nukesor/pueue#364]
Is is possible to get the process ID of a given task? 

I've checked the json output and havent seen anything there?

cheers

**Comment by Nukesor** [comment]
This isn't possible yet, since this can also be quite confusing.

Since we're using a shell as an executor backend, there can be multiple pids at once, pids can change rapidly and under Mac this doesn't work at all since no-one wrote a library to get child process IDs yet :D

I'm not sure if this is something we should expose via the Json output, as it feels like this info should only be used by the scheduler that's actually responsible for handling these jobs.

What's your usecase if I may ask :)?

**Comment by Nukesor** [comment]
Ping @getsec

**Comment by getsec** [comment]
@Nukesor - Apologies for the late reply. I was looking to use this in a platform I run to manage long running proceses. Previously, we used some basic python async subprocess modules to launch long running proceses and stored / managed process ID's in a database. Since then, I've actually switched from using process Ids to using the pueue task IDs, I don't think this is needed to be open anymore

**Comment by Nukesor** [comment]
Perfect :)
Thanks for the clarification!
