### ISSUE TITLE
Enable to remove all groups

### ISSUE THREAD

**Issue by allencho1222** [Nukesor/pueue#428]
### A detailed description of the feature you would like to see added.

I hope `pueue` enables us to remove all groups where jobs are not running.

Currently, `pueue` only supports removing a group by a given group name.

### Explain your usecase of the requested feature

I usually use `pueue` in a script that launches **work** consisting of multiple `pueue` jobs.

The work, here, corresponds to the **group** used by `pueue`.

However, after launching multiple **works**, it is quite troublesome to remove all groups if I do not use a tool like `awk`.

I hope `pueue` itself has the ability to remove all group names.

**Comment by Nukesor** [comment]
To be honest, I don't think that this is a usecase for a new commandline option.

Your usecase sounds like you're heavily relying on scripting to add and remove large amounts of jobs that're then split into several groups.

Since I don't see this in a "normal" usecase scenario and since this is easily scriptable, you should probably do it that way.

Hoewver, I'm open to exposing the list of groups via json.
That way, you can iterate through all groups, check for each group via `pueue status -g $group -j` whether there're any tasks and delete it, if they're not.

**Comment by allencho1222** [comment]
Hi, @Nukesor 

I'm sorry, I couldn't understand what you mean.

There's no option `-j` for `pueue group`.

Does it mean that are you open to support the option like `pueue group -j`.

If such option is available, it would be nice.

I currently do my job by using:

`pueue group | awk '{print $2}' | xargs -n 1 pueue group remove`

**Comment by Nukesor** [comment]
Yes, I offering to add a `-j` option for the `pueue group` subcommand, so it's easier to do scripting :)

**Comment by allencho1222** [comment]
Hi, @Nukesor 

Thank you. I really appreciate it.

**Comment by Nukesor** [comment]
I'll track this in the newly created issue to avoid confusion :)
