### ISSUE TITLE
Make pueue be able to create pty by request

### ISSUE THREAD

**Issue by neg-serg** [Nukesor/pueue#435]
### A detailed description of the feature you would like to see added.

Overall UX is good enough.

I am almost ready to get rid off tmux.

But compared to using tmux and other multiplexers, you need to consider whether the task is long or not, which is not always possible. There is reptyr to get rid of this, but in this case it is not applicable, since there is no terminal. It would be interesting to optionally be able to create a pty to be able to enqueue already running tasks.

### Explain your usecase of the requested feature

1. The task, which was not expected to be long, turned out to be long.
2. Ability to add interactive applications. In theory, it is enough to be able to create /dev/pts. Surely there are already ready-made solutions or libraries in the rust for this.

**Comment by Nukesor** [comment]
This is actually very close to the feature request of https://github.com/Nukesor/pueue/issues/397
Pueue is indeed not designed for interactive processes and most likely won't be for the future.

However, I would very much like to have some kind of process manager with an interactive shell :D
As I said in the other issue, I would love to have something like this to manage my game servers^^

I'll close this for now, as this functionality won't be natively added to pueue and is also out of scope, since pueue is designed for task execution of tasks that'll finish at some point.
This feature would allow it to be used in different ways it was never intended to be used :)
