### ISSUE TITLE
Improve `pueue follow` behaviour with a task that does not yet have logs

### ISSUE THREAD

**Issue by fluffysquirrels** [Nukesor/pueue#436]
### A detailed description of the feature you would like to see added.

1. I want `pueue follow ${TASK_ID}` to exit with code != 0 when it cannot find a task log with that ID.

These are the lines that would need to be changed:
https://github.com/Nukesor/pueue/blob/facfb2bafd5b1c87502b58441ba4c4c3c16f4395/pueue/src/client/display/follow.rs#L30-L33

Ideally, these would also be implemented, but if change 1 above was done, these could be implemented in a wrapper script:

2. If `${TASK_ID}` is currently queued (but not yet running), `follow` would wait for `${TASK_ID}` to start and then follow the logs as normal. (This behaviour could be optional)
3. Add a new argument `--follow` to `pueue add` that automatically runs `pueue follow ${TASK_ID}` after the task is added.

Currently if the task log is not present, `pueue follow` will print a human-readable error message, but exit with code 0 (success).

### Explain your usecase of the requested feature

I am adding a task from a script, and I want to follow the log output for that task.

### Alternatives

As a workaround, my wrapper script would have to:

* `pueue add` the task
* `pueue wait --status Running ${TASK_ID}`
* `pueue follow ${TASK_ID}`

### Additional context

If you like the sound of these features, I can implement them and submit a PR. Let me know :)

**Comment by Nukesor** [comment]
Hey :) 

I implemented points 1. and 2. in the linked PR.
If a task gets removed or doesn't exist in the first place, the exit code is now `1`.

Also, if a task exists but didn't start yet, the client will wait for the task to start/finish instead of immediately exiting.
I see how this is an obvious UX improvement.

I'll have to write a few tests for this, since there're a few edge-case scenarios that I want test coverage for, but as far as I can see, it seems to work as expected. Feel free to check the branch.

**Comment by Nukesor** [comment]
I added some tests and I'm pretty confident that your requested change works as expected.

I'll go ahead and merge, but it would be great, if you could give this a test run.
