### ISSUE TITLE
Tags and Task grouping

### ISSUE THREAD

**Issue by fez909** [Nukesor/pueue#44]
I love the simplicity of pueue so I'm hesitant to ask for this, but I feel it would be really useful.

Scenario:

Multiple long-running jobs queued. Some are IO bound, some CPU bound. I only want one of each to run at any one time, but the only way I can manage this currently is by switching jobs around and tweaking the maxProcesses config value ocassionally. 

For example, if I don't check the queue status in time and 2 'CPU jobs' are running and no 'IO jobs', then I switch jobs so that the next job is IO, and set maxProcesses to 3, then immediately back to 2.

Unless there is already a better way to handle this that I'm missing?

**Comment by Nukesor** [comment]
Wow hey!

Sorry that I'm only now responding to your ticket. Somehow I totally missed that you created it...

I already thought about implementing multiple queues a long time ago, but I didn't really know how to implement it without making the UI crowded or the commandline interface confusing :/

The most simple way right now to imitate this behaviour would probably be to run two separate pueue instances. You can achieve this by specifying a different root directory, which can be easiliy done with an alias.

To be honest, I don't think, that I will implement this feature in pueue, since I'm already working on a rewrite in Rust [pueue-rs](https://github.com/Nukesor/pueue-rs). Frankly, this is taking a while since I'm learning the language by the way.

But I'm planning to add a multiple queue feature to the rewrite, as well, as a proper remote client communication via TCP. Another cool feature of Rust would be that pueue would become cross platform.

Sorry again for only noticing this issue now...
But thanks for using pueue :) I appreciate it!

**Comment by Nukesor** [comment]
Now that I'm thinking about it, I think it could be implemented without a big rewrite and even without polluting the interface, if this feature stays completely optional.
So if you are really interested in this feature, feel free to hack around a little, I'll be happy to help!!

**Comment by fez909** [comment]
Thanks. I think it might be beyond my knowledge but I'm about become a lot less busy so I'll have a look through and see if I can get my head around it.

**Comment by Nukesor** [comment]
Hey everyone!
The rewrite is happening (just pushed the first version to master).
I thought a lot about groups and how to implement them, but I didn't come up with a solution I'm satisfied yet.

The current version implements the same feature set as the old pueue (maybe a little bit more and with better consistency).

When I'm done polishing, I'll probably start working on this.

**Comment by Nukesor** [comment]
@fez909 I'm thinking.
Do you need groups, in terms of multiple queues or would it be enough to tag a task with e.g. `cpu`, `hdd` and specify a distinct amount of allowed parallel tasks per tag?

**Comment by fez909** [comment]
> @fez909 I've been thinking.
> Do you need groups, in terms of multiple queues or would it be enough to tag a task with e.g. `cpu`, `hdd` and specify a distinct amount of allowed parallel tasks per tag?

For my use case, the tagging idea sounds like it would work.

If I was building it, I would have a default queue and named queues. All commands apply to the default queue unless otherwise specified.

```bash
# Adding to the main queue
$ pueue add ~/long_running_script.sh
-> Task added to default queue

# Creating a named queue
$ pueue -q cpu add ~/long_running_script.sh
-> Task added to named queue 'cpu'

# Checking status of name queue
$ pueue -q cpu status 
-> JobID 1 running ~/long_running_script.sh from ~

# Updating number of parallel tasks on named queue
$ pueue -q hdd config maxProcesses 3
-> Named queue 'hdd' config updated successfully
```
etc., etc

**Comment by Nukesor** [comment]
I quite like this approach.
This would need quite a bit of extra handling, but I think it's managable.
I think I'll start working on this, as soon as the new pueue is properly polished.
Right now there are still a few things left to do.

**Comment by Nukesor** [comment]
A draft for grouping is implemented in https://github.com/Nukesor/pueue/pull/91

Feel free to check it out. I'm happy about any reviews.
