### ISSUE TITLE
How to exit `follow` without shutting down the daemon

### ISSUE THREAD

**Issue by SpacewaIker** [Nukesor/pueue#442]
### A detailed description of the feature you would like to see added.

When executing `pueue follow X`, I can see the log of currently-running task X. But how can I exit the follow command (i.e. get back to my shell) without shutting down the daemon? The only thing I've found that seems to do anything is `<C-c>`, but this shuts down the daemon for some reason. 

### Explain your usecase of the requested feature

Not sure if I'm using pueue for its intended purpose but I wanted to use it to run a testing/development backend server. I usually just open another tab in my terminal where I just `cargo run` my backend, but I thought that it would be more practical to use pueue. Just create a task that starts the server, then I can `follow` whenever I need to look at the log, and get back to my shell after getting the info I needed. That way, the server runs in the background and doesn't clutter my windows.

Also, maybe I should make a new issue for this, but is it possible to define a group of tasks that I can start with one command and stop with another (e.g. a backend server and a frontend server)? A paused task becomes failed when shutting down the daemon so that doesn't work, and I don't see a way to stop or shutdown a task that has no "end" (like a server) without it becoming "failed".

**Comment by Nukesor** [comment]
May I ask, which version of pueue you're using (or which OS)?
Especially the PID file issue should be fixed since quite a long time, since the PID is now located in the runtime directory, which is automatically cleared on reboot (at least on unix).

Regarding the `C-c`, this is pretty much the scenario I expected.
Your terminal somehow also sends the SigInt to the `pueued` process, which shouldn't happen.
`pueued` just receives the sigint and reacts as expected and desired, by shutting down.

I strongly suggest to either investigate why your terminal behaves that way, or to simply start `pueued` as a service via systemd user services or alike.

**Comment by SpacewaIker** [comment]
I'm using Pueue client version 3.1.2, downloaded through scoop, on windows 11. The PID file path was `C:\Users\username\AppData\Local\pueue\pueue.pid`. I don't know if this is supposed to be cleared or not when windows reboots.

**Comment by Nukesor** [comment]
Ahh I see.
AFAIU, there's no `XDG_RUNTIME_DIR` in a `tmpfs` equivalent for Windows.

I'm open to suggestions on how to handle/prevent such scenarios on Windows, since I'm not familiar what the ideomatic approach to this problem is.

**Comment by SpacewaIker** [comment]
I see, thanks for the help!
