### ISSUE TITLE
Release .deb 

### ISSUE THREAD

**Issue by Flova** [Nukesor/pueue#446]
### A detailed description of the feature you would like to see added.

Installing pueue under Arch etc. is quite easy as it is distributed via the the package manager. Installing it under Ubuntu could be easier. I understand that releasing stuff into the official package sources is probably out if scope in the near future, but it would be nice to have a released `.deb` file that includes both the daemon as well as the client and handles the systemd service setup. The steps themselves are pretty easy (the binaries are released), but it would improve the convenience. We currently build the `.deb` manually ourselves for internal deployment, but that's rarely done, so our version is quite outdated. It would also improve the setup for beginners.

### Explain your usecase of the requested feature

Easier installation with only one command (two including package download). The packaging could be integrated into the GitHub action which is responsible for the binary releases.

### Alternatives

Keep it as it is or add a simple setup bash script that performs the required commands.

**Comment by Nukesor** [comment]
I agree that it would be awesome to have Pueue available in debian based official repositories :)

But having just a `.deb` file without uploading it to a repository doesn't feel right, especially since every distribution would drop by and demand their own package format to be released.
The packaging process for distributions is usuall disjoint from the actual release process of upstream repositories, which I quite like, since it keeps the actual integration work out of the upstream project.
I really don't feel comfortable to maintain a bunch of packaging logic for distributions I don't use.

Since I'm not rolling any debian based distros on my own, it would be awesome if somebody could take care of packaging the project. Do you by any chance know a good packager for debian who would step up and push integration of Pueue in the official repositories?

**Comment by Nukesor** [comment]
I would probably be ok with a build script in the `utils` folder, but I'm not very comfortable with having some logic in the CI release workflow that I cannot debug myself. Stuff like that sometimes just breaks (it already happened with the current release logic) and I don't want to depend on other people in such a situation, since this might result in a broken/semi-finished release for a few days.

**Comment by Nukesor** [comment]
Ping @Flova

Would a build script in the utils folder help you out? I would also be interested in your infrastructure setup, since it sounds like you're running your own debian package repository?

**Comment by Nukesor** [comment]
Closing for now :)
