### ISSUE TITLE
Support Editing Priority

### ISSUE THREAD

**Issue by JP-Ellis** [Nukesor/pueue#449]
### A detailed description of the feature you would like to see added.

TL;DR: I would like to be able to edit the priority of a task within the queue.

The recent release of pueue added support for a `--priority` flag to the `pueue add` command. It would be great to be able to also edit the priority.

### Explain your usecase of the requested feature

For example, if I have recently added an item to the queue but forgot to set it to a high priority, I would be able to execute `pueue edit --priority 9 126`.

### Alternatives

At the moment, the only alternative I can think of is to remove and re-add the task with a higher priority.

**Comment by Nukesor** [comment]
I already assumed that this request would pop up :D

Yep, this is definitely a missing feature and should also be fairly easy to do :)

**Comment by Nukesor** [comment]
Here's a thought.
What do you think about making the editing process a bit more accessible and less cumbersome.

I'm currently thinking about exposing all editable properties of a task into temporary well-formatted file (probably YAML, since we're already heavily using this).
One would then just go ahead and call `pueue edit $TASK_IDS` and a single editor instance would be spawned from which the whole task could be edited in a single view.

**Comment by Nukesor** [comment]
On a second thought, this would go hand-in-hand with issues due to YAML's reserved characters and multiline formatting.


I would really like to have a single screen where users can edit all properties of a task, but I'm not sure how this could be achieved without being too hacky...

The current approach via flags just feels a bit clunky. Having multiple editors popping up to edit a single task really isn't convenient at all.

**Comment by JP-Ellis** [comment]
I think there's merits to both methods.

To have a single screen where users can edit all properties of a task sounds great for situations when I want to interactively edit everything. As to achieving this, I think a method similar to `sudoedit` might be good. That is, use a temporary file and open up the user's favourite editor to make edits. The temporary file in this case would contain a JSON or YAML representation of the tasks. You would need to handle a bit of logic to validate the input, and decide how much you just want to trust end users or not. I do suspect this might be a bit more involved to implement.

The alternative of using flags lends itself nicely to edit a single property easily, and more automated workflows (e.g., `xargs`). I do agree that it runs the risk of adding _a lot_ of flags though. Two things I can think of:

- Be a bit selective as to which flags you want to support. For example, editing the priority seems like a bit of a no-brainer to me. Editing the task itself however seems prone to error and might be better suited to just deleting the task and adding a new one.
- Hiding a lot of the flags behind an `--help-all` or similar flag. This way, the help text isn't overloaded with hundreds of flags, but these can still be discovered relatively easily and access very easily.
- Using a two-argument flag of the form `pueue edit X --property foo val1 --property bar val2`. This avoids having too many flags, but also provides a lot of flexibility.

**Comment by Nukesor** [comment]
Closing for now, as this has been implemented.
