### ISSUE TITLE
Error on checking status: "pickle data was truncated"

### ISSUE THREAD

**Issue by tdhopper** [Nukesor/pueue#47]
The data store appears to be corrupted for my installation of pueue. When I run, `$ pueue status`, I get this error:

```
$ pueue status                                                                                                                                         Tue Jun 18 16:50:01 2019
Traceback (most recent call last):
  File "/Users/thopper/.local/bin/pueue", line 11, in <module>
    load_entry_point('pueue==1.0.4', 'console_scripts', 'pueue')()
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/__init__.py", line 69, in main
    args.func(args_dict, root_dir)
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/client/displaying.py", line 32, in execute_status
    status = command_factory('status')({}, root_dir=root_dir)
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/client/factories.py", line 42, in communicate
    response = receive_data(client)
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/client/socket.py", line 21, in receive_data
    response = pickle.loads(answer)
_pickle.UnpicklingError: pickle data was truncated
```

That also kills the pueue process:

```
2019-06-18 16:52:41,969 - root - ERROR -
Traceback (most recent call last):
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/daemon/daemon.py", line 255, in main
    self.respond_client(response, waiting_socket)
  File "/Users/thopper/.local/pipx/venvs/pueue/lib/python3.7/site-packages/pueue/daemon/daemon.py", line 124, in respond_client
    socket.sendall(response)
BlockingIOError: [Errno 35] Resource temporarily unavailable
```

I'm using `Python 3.7.3`.

**Comment by Nukesor** [comment]
Hmm. This is weird. The Socket is configured to be non-blocking.
Removing the `~/.config/pueue/queue` file should fix this problem.
The only reason I can think of right now, is that the `queue` file is somehow too big, but pueue should support arbitrary file sizes...

I really don't know how this could happen.

**Comment by alextooter** [comment]
I got the same error.
When add 5 or more download task to pueue,each has a aria2c running a http download, max running queue set to 3.The whole system is very busy,then call 'pueue status',it didn't return,then print the same error information as tdhopper.

So it looks like when dealing with big network traffic,call the status will fail.In my case,download speed it 13MB/s @i7 3.2G

**Comment by Nukesor** [comment]
External download speed shouldn't be a factor with this, since pueue uses unix sockets and is thereby not bound to any outgoing traffic.
I have another idea:
It sounds like you are operating something like a scraper that get's a lot of arbitrary input from the web and probably also outputs a lot of arbitrary information into the log output.
Maybe there is some information, that's somehow malformed utf8 or some other weird format, that cannot be properly pickled.

Could you verify some of my thoughts? Is there something special in your log output you could think of?
You can look at the log outputs of the individual processes in `.config/pueue` while they are running. (On second thought, these should be placed into `.local/share/pueue` as well...)

I already thought about using something else than pythons `pickle`. Probably `json`.

I'm still waiting for Rusts stabilization of `async` and proper crate support, but it looks like it will still take some time, before I can rewrite pueue in Rust. I'll try to reproduce this issue until then and if I find the case, fix it.

**Comment by alextooter** [comment]
@Nukesor I check the log,it works fine with some Chinese characters.(I didn't do pueue status during download task,then check the log file.)

I just remember how I introduce this problem, try modify pueue.ini last night, change logTime = 1209600 to 12096, which may cause this happen.After change it back to 1209600,add ten more download task pueue works fine,pueue status return correct information during downloading.

So I guess @tdhopper doing the same thing to pueue.ini,change the log clear time to 3min cause this problem.

**Comment by Nukesor** [comment]
Uhh that's interesting. I'll look into it tomorrow! Thanks for the information :)
