### ISSUE TITLE
Feature request - ncurses interface

### ISSUE THREAD

**Issue by mvrozanti** [Nukesor/pueue#49]
First of all, thank you for this. I've been using pueue because it makes for a nifty way to be more productive. I was wondering if an ncurses interface is a wanted feature. I think it would be awesome, specially if it can get commands by opening the default editor or some tricks like that. It would definitely attract some more stars.

On the other hand, it's kind of unnecessary/bloat and might be a bit lenghty thing to implement. What are your thoughts on this?

**Comment by Nukesor** [comment]
Well, Investigating the queue, looking at logs and checking the current output could become pretty cool with this, but on the other hand this would require quite some work.

I'm pretty sure that I won't implement this features, especially since I'm planning to rewrite pueue in Rust as soon as the async language feature is stable.

Anyway, I would be happy to help you with the implementation! If you have any questions, feel free to ask!

**Comment by Nukesor** [comment]
Since the rewrite is here, this could be probably realised with https://github.com/fdehau/tui-rs

I would love this functionality!

**Comment by mvrozanti** [comment]
Hey that's cool, didn't know that repo existed. I've never actually written anything in rust and I got no time lately so I'm not sure if I'm the guy to do it either but I will be watching pueue closely for updates!

**Comment by quebin31** [comment]
It's a nice idea, probably the best use case for the ncurses ui is to check the logs in real-time if by means your script is constantly printing information that you need to check.

**Comment by Nukesor** [comment]
Indeed. It's mostly something that looks nice at this point.
Though, it could be useful for ergonomic status-changes (stash, enqueue) and command/path edits.

A live-view of the status could also make a pretty cool dashboard.

**Comment by she3o** [comment]
Hi, I just want to say that building TUIs seems like a good first issue for Rustacean wannabes. I will finish my college exams by the end of March. If by then, this was not already being worked on, I pledge to learn enough Rust to implement it by summer!

**Comment by Nukesor** [comment]
Nice!

I exported the shared code between the daemon and the client into the stand-alone `pueue-lib` library. It might be a little rough around the edges regarding error handling, but i tried to document it as well as possible.

It's probably best to create a stand-alone `pueue-tui` client, which uses this library instead of adding that code to the `pueue` binary.
The tui code would be completely separated from the remaining `pueue` client code anyways.

**Comment by Nukesor** [comment]
Feel free to start hacking on this project any time!

**Comment by nothingnesses** [comment]
In the meantime, I wrote a shell script that uses [`jq`](https://github.com/stedolan/jq) and [`skim`](https://github.com/lotabout/skim) to provide interactivity and fuzzy-finding facilities:

```shell
#!/bin/sh
pueue_select() {
	printf "%s\n" "${1}" | jq -r '.[] | "\(.id) , \"\(.command)\" , \"\(.path)\" , \"\(.group)\" , \(.status) , \(.start)"' | sk --header "Select processes (id , command , path , group , status , start):" -m ;
}

pueue_ids() {
	selections="$(pueue_select "${1}")" ;
	line_count="$(printf "%s\n" "${selections}" | wc -l)" ;
	counter=1 ;
	accumulator="" ;
	printf "%s\n" "${selections}" | while read -r line ; do
		accumulator="${accumulator:+${accumulator} }${line%% *}" ;
		if test "${counter}" -eq "${line_count}" ; then
			printf "%s\n" "${accumulator}" ;
		fi ;
		counter=$((counter + 1)) ;
	done ;
}

pueue_selections() {
	with_commas="$(printf "%s\n" "${2}" | tr ' ' ', ')" ;
	printf "%s\n" "${1}" | jq -r ".[] | select(.id == (""${with_commas}"")) | \"\(.id) , \(.command) , \(.path) , \(.group) , \(.status) , \(.start)\"" ;
}

pueue_wrapper() {
	tasks="$(pueue status -j | jq -j '[.tasks | to_entries[] | [.value] | .[] | { id: .id, command: .command, path: .path, group: .group, status: .status, start: .start }]')" ;
	ids="$(pueue_ids "${tasks}")" ;
	if ! test -z "${ids}" ; then
		printf "Selections:\n%s\nInput subcommand and arguments: " "$(pueue_selections "${tasks}" "${ids}")" ;
		read -r input ;
		pueue ${input} ${ids} ;
	fi ;
}

```

It's ugly and dumb (hard-coded JSON keys), but I figured it's fine just as a stop-gap. 🤷‍♂️

One way to install it would be to copy the functions to something like your `~/.profile` (assuming that's sourced by your shell). It can then be used by calling the `pueue_wrapper` function.

**Comment by mvrozanti** [comment]
@nothingnesses I really like this idea. It seems even lighter than a ncurses depency and still as sufficient.

**Comment by nothingnesses** [comment]
@mvrozanti It's dependent on `jq`, `skim` and `tr` (GNU coreutils), so I'm not sure that it is lighter. Presumably, it also won't work on non-POSIX shells, so it's probably useless to Windows users. But I'm glad you found it sufficient.

**Comment by nothingnesses** [comment]
Since `skim` is also a Rust library, perhaps it could be integrated with `pueue` natively in the future?

On a related note, there's also [`tab-rs`](https://github.com/austinjones/tab-rs) which is another multiplexer written in Rust but which has an interactive fuzzy-finder built-in (although it lacks pueue's job-queueing facilities and more informative interface) and was what inspired me to write the `skim` script above. It seems like a combination of `pueue` and `tab-rs`' features would make for the ideal multiplexer and I'm wondering if somehow a collaboration from those involved with both projects would be feasible to make such a thing a reality. Afaik, the developer of `tab-rs` seems [open to implementing an interface similar to `pueue`'s](https://github.com/austinjones/tab-rs/issues/344#issuecomment-816864689) that shows the processes' working directories and command histories, so perhaps a collaboration towards a single multiplexer tool would be more efficient and maybe prevent duplicate/redundant work?

**Comment by clemera** [comment]
It would be great if one could a pass a flag to pueue so it returns the output as JSON. This would allow to easily build TUIs for other clients like Emacs.

**Comment by nothingnesses** [comment]
> It would be great if one could a pass a flag to pueue so it returns the output as JSON. This would allow to easily build TUIs for other clients like Emacs.

You mean with like `pueue status -j which is already used in the script I linked above? Or did you have something different in mind?

**Comment by clemera** [comment]
Oh great! Sorry for the noise that should do it :+1:

**Comment by d33tah** [comment]
Here's a quick idea on how to proceed without necessarily creating a new TUI as the first step: recommend using `watch` somewhere in `--help`. For example, `watch pueue status` is going to give you a quick update on the status of the queue.

`pueue status` could also have a couple of features that would nicely pair with `watch`:

1. an equivalent of `--raw-control-chars` from `less`: allow the project to spit out ANSI escape sequences even if stdout is a pipe, so that it can be coupled with `watch --color`,
2. don't print ANSI sequences if stdout is a pipe and `--raw-control-chars` was not specified - right now it's a mix: it looks like there was intent not to print them, but the first line contains them,
3. add a way to compact the output of pueue status, right now lots of vertical space is wasted on separators,
4. add a way to display `pueue status` as if `pueue clean` was called - i.e. only running things would be displayed

**Comment by Nukesor** [comment]
I'm going to close this issue for the time being, as this has been open since ~3 1/2 years.

We already got the emacs interface by @xFA25E  and if somebody wants to built a new stand-alone ncurses interface, i think it's best to start a new issue from scratch, as quite bit of stuff happened since this issue was opened :)

Best wishes and happy new year to everyone still subscribed to this issue ;D

**Comment by tekumara** [comment]
I've created a TUI for pueue called [pui](https://github.com/tekumara/pui). It doesn't have fuzzy search yet but I'd like to add it.
