### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by rayanamal** [Nukesor/pueue#539]
### Describe the bug

Even though the [Get Started guide](https://github.com/Nukesor/pueue/wiki/Get-started#start-the-daemon) in the wiki says there's a systemd unit file in the github releases page, there is none. This is probably the 4th time I checked over the course of this year and it's nowhere.

> Download pueued.service from the GitHub Releases page.

### Steps to reproduce

Check out the releases page.

### Operating system

NixOS Unstable

### Pueue version

v3.4.1

**Comment by Nukesor** [comment]
Good point. The systemd unit file is usually uploaded during the linux x86-64 release, which was broken until recently.
Since the build failed, the systemd service file was never uploaded.
With the release pipeline being fixed in (https://github.com/Nukesor/pueue/pull/538), this should now be done automatically once again.

The systemd service file is also located in the repo and just copied over during the release process for convenience.
See https://github.com/Nukesor/pueue/tree/main/utils

I also added the file to the latest release again.
