### ISSUE TITLE
Consider updating Wiki for rust issue 39364

### ISSUE THREAD

**Issue by ChocolateOverflow** [Nukesor/pueue#546]
https://github.com/Nukesor/pueue/wiki/Advanced-usage#scripting mentions that scripts may need to sleep until [rust issue 39364](https://github.com/rust-lang/rust/issues/39364) is fixed.
The issue has been closed as completed. Is the sleep still necessary, or will you remove that little note?

**Comment by Nukesor** [comment]
It's actually still relevant due to the current architecture of pueue.

The need for sleep (:D) will become obsolete for as soon as this: https://github.com/Nukesor/pueue/issues/540#issuecomment-2162316875 is implemented.
Once that has been done, a lot of documentation needs to be updated anyway, including the wiki.

Anyhow, I removed the mention of the rust issue for now :)
