### ISSUE TITLE
[Bug] The more tasks are queued, the more the performance of adding tasks decreases.

### ISSUE THREAD

**Issue by lepapareil** [Nukesor/pueue#573]
### Describe the bug

Adding 500 tasks to an empty group takes a certain amount of time, but adding an additional 500 tasks takes more time, and so on.

### Steps to reproduce

Start pueued, add test group and add 500 tasks 5 times :

```
pueued -d
pueue group add test
pueue pause --group test
for count in $(seq 5) ; do
    echo -e "\n${count} - adding 500 tasks"
    time for task in $(seq 500); do
        pueue add --group test "echo ${task}" >/dev/null 2>&1
    done
done
```

We can see that adding 500 tasks in an empty paused group takes `~2 sec`, but adding more 500 tasks takes `~4.5 sec` etc...

```
Group "test" is being created
Group "test" is being paused.

1 - adding 500 tasks

real    0m2.282s
user    0m0.730s
sys     0m0.166s

2 - adding 500 tasks

real    0m4.773s
user    0m0.871s
sys     0m0.179s

3 - adding 500 tasks

real    0m7.317s
user    0m0.783s
sys     0m0.210s

4 - adding 500 tasks

real    0m10.070s
user    0m0.747s
sys     0m0.189s

5 - adding 500 tasks

real    0m12.247s
user    0m0.772s
sys     0m0.172s
```

### Operating system

Ubuntu 22.04 amd64

### Pueue version

v3.4.1

**Comment by Nukesor** [comment]
That's because the task state is serialized and written to disk, which takes a certain amount of time.
The bigger the state file and the more needs to written to disk, the longer it takes.

Pueue isn't designed to be heavy duty task scheduler with an complex transactional state representation, so having lots of tasks will take longer amounts of time.

Furthermore, Pueue isn't designed to be used for micro tasks. It's specifically designed to handle a relatively small amount of long running tasks. For your usecase, there might be other and better suited tools out there. Check the https://github.com/Nukesor/pueue?tab=readme-ov-file#similar-projects section.

**Comment by lepapareil** [comment]
Got it, thanks for your work!
