### ISSUE TITLE
Better support for Cygwin

### ISSUE THREAD

**Issue by mvanleeu** [Nukesor/pueue#92]
**Is your feature request related to a problem? Please describe.**
Under Windows, powershell is used as the default shell, but this makes it quite cumbersome if the use case is rather use/stay in the Cygwin environment.

**Describe the solution you'd like**
When pueued would be started "the cygwin way", the default shell coudl be cygwin's bash instead of powershell.. In the meantime, a section in the FAG describing how to use pueue if one wants to enqueue commands accessible via cygwin / bash.

**Describe alternatives you've considered**
Trying out the the python version of pueue, if I cna find it and get pip to work under cygwin.

**Additional context**

**Comment by Nukesor** [comment]
There's the idea to allow customized commands that will be used to invoke the task https://github.com/Nukesor/pueue/issues/51 .
This would probably solve your problem, since this allows users to use other shells.

However, this is something that'll most likely not be built by me.
I'm not using Pueue on Windows and I'm pretty happy with bash as a default shell on Unix systems.

Feel free to tinker around and create a PR, though :)
If you do so, please try to still support Powershell and make everything configurable. The configuration logic should be Windows only as well.

**Comment by Nukesor** [comment]
The legacy version can be found over here:
https://github.com/Nukesor/pueue-python-legacy

Pueue has been removed from pypi, as it led to some confusion.

**Comment by Nukesor** [comment]
Ah.
I just remembered. The python version didn't have Windows support at all.

**Comment by Nukesor** [comment]
Closing due to missing response from issue creator
