### ISSUE TITLE
Limit multiprocessing

### ISSUE THREAD

**Issue by pranavashok** [Nukesor/pueue#97]
I have some scientific code which generates hundreds of run jobs at a time. Each instance tries to spawn as many threads as available CPU cores, however, for runtime benchmarking reasons, I restrict each job to a single core using the `taskset -c` command. I use pueue to manage the jobs as follows:

```
pueue add -g cpu35 -- "taskset -c 35 /usr/bin/time -v command1
pueue add -g cpu36 -- "taskset -c 36 /usr/bin/time -v command2
pueue add -g cpu37 -- "taskset -c 37 /usr/bin/time -v command3
pueue add -g cpu38 -- "taskset -c 38 /usr/bin/time -v command4
pueue add -g cpu39 -- "taskset -c 39 /usr/bin/time -v command5
pueue add -g cpu35 -- "taskset -c 35 /usr/bin/time -v command6
pueue add -g cpu36 -- "taskset -c 36 /usr/bin/time -v command7
pueue add -g cpu37 -- "taskset -c 37 /usr/bin/time -v command8
pueue add -g cpu38 -- "taskset -c 38 /usr/bin/time -v command9
pueue add -g cpu39 -- "taskset -c 39 /usr/bin/time -v command10
...
```
where each group cpu35, cpu36 etc. have their parallel counts set to 1. This works great, until for example, `command1` is taking forever to run. In that case, it blocks `command5` from starting even if all the other jobs have finished running and CPUs 36-39 are free.

**Describe the solution you'd like**
It would be great to have a way to make pueue manage the CPU affinity instead of having to generate the `taskset -c <x>`  in advance. Whenever pueue decides to run a queued task, it could look for the CPUs that are not assigned to any of the running tasks and run the new one on this particular CPU. Do you think pueue would benefit from such a feature?

**Comment by Nukesor** [comment]
Hm. I don't think that pueue should handle cpu affinity. That feels like it should be handled by the underlying process.

Why don't you limit the number of threads inside the actual command to a single process.
You could then spawn all commands, that should be run on a single processor, in one group and then limit the group to the amount of cores.


If you can ensure that `command1` only uses a single thread, you could then set the limit for group `cpu1` to 5 (since it has 5 cores).

There won't be any bottleneck due to blocking tasks.
The only bottleneck in this sceneario would be a tasks that continues running, when every other process is finished.

pueue parallel -g cpu1 5
pueue add -g cpu1 -- command1
pueue add -g cpu1 -- command2
pueue add -g cpu1 -- command3
pueue add -g cpu1 -- command4
pueue add -g cpu1 -- command5
pueue add -g cpu1 -- command6
pueue add -g cpu1 -- command7
pueue add -g cpu1 -- command8
pueue add -g cpu1 -- command9
pueue add -g cpu1 -- command10


That's how a normal worker/thread pool works and it sound exactly like the solution you're looking for.

In case you cannot specify the amount of threads in your `commandX`, that's a problem with your command and not with pueue.

**Comment by pranavashok** [comment]
> If you can ensure that command1 only uses a single thread, you could then set the limit for group cpu1 to 5 (since it has 5 cores).
> ...
> In case you cannot specify the amount of threads in your commandX, that's a problem with your command and not with pueue.

This is indeed the case - it is a large scientific tool which doesn't allow one to specify the number of threads. And I guess you're right, I should rather send this feature request to the developers of that tool. 

Thanks for your time and pueue!

**Comment by Nukesor** [comment]
You're welcome :)

I'm curious, which program are you using?

**Comment by pranavashok** [comment]
It's a modified version of [PRISM Model Checker](https://github.com/prismmodelchecker/prism).
